package soft.bigeran.dervis.EvliyalarAnksiklopedisi;

import android.animation.Animator;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.inputmethod.InputMethodManager;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.SearchView;
import androidx.appcompat.widget.Toolbar;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.blogspot.atifsoftwares.animatoolib.Animatoo;

import java.util.ArrayList;

import soft.bigeran.dervis.R;

public class MainActivitySearchView extends AppCompatActivity {


    String[] number = {"&1=Abapûş-i Velî=ıbıpısı vılı	",
            "&2=Abbâdî=ıbbıdı	",
            "&3=Abbâs Bin Hamza En-nişâbûrî=ıbbıs bın gımzı ınnısıbırı	",
            "&4=Abbas Mehdi=ıbbıs mıgdı	",
            "&5=Abdil Dede=ıbdıl dıdı	",
            "&6=Abdullah Bin Abdülazîz=ıbdıllıg bın ıbdılızız	",
            "&7=Abdullah Bin Abdülazîz (Osman) El-yuneynî=ıbdıllıg bın ıbdılızız ısmın ılyınıynı	",
            "&8=Abdullah Bin Abdülganî El-makdisî=ıbdıllıg bın ıbdılgını ılmıkdısı	",
            "&9=Abdullah El-acemî=ıbdıllıg ılıcımı	",
            "&10=Abdullah Bin Avn=ıbdıllıg bın ıvn	",
            "&11=Abdullah Ayderûsî=ıbdıllıg ıydırısı	",
            "&13=Abdullah-ı Dehlevî=ıbdıllıgı dıglıvı	",
            "&14=Abdullah Bin Dînar=ıbdıllıg bın dınır	",
            "&15=Abdullah Bin Ebû Bekr El-ayderûs=ıbdıllıg bın ıbı bıkr ılıydırıs	",
            "&16=Abdullah Bin Ebû Huzeyl El-anezî=ıbdıllıg bın ıbı gızıyl ılınızı	",
            "&17=Abdullah Efendi=ıbdıllıg ıfındı	",
            "&18=Abdullah Efendi (Himmetzâde)=ıbdıllıg ıfındı gımmıdzıdı	",
            "&19=Abdullah-ı Ensârî=ıbdıllıgı ınsırı	",
            "&20=Abdullah Fahri Baba=ıbdıllıg fıgrı bıbı	",
            "&21=Abdullah Bin Gâlib=ıbdıllıg bın gılıb	",
            "&22=Abdullah-ı Gürcistânî=ıbdıllıgı gırcısdını	",
            "&24=Abdullah Haddâdî=ıbdıllıg gıddıdı	",
            "&25=Abdullah Harrâz=ıbdıllıg gırrız	",
            "&26=Abdullah Hasîb Yardımcı=ıbdıllıg gısıb yırdımcı	",
            "&27=Abdullah Hayderî=ıbdıllıg gıydırı	",
            "&28=Abdullah Bin Hâzır=ıbdıllıg bın gızır	",
            "&29=Abdullah Herâtî=ıbdıllıg gırıdı	",
            "&30=Abdullah Bin Hıdır Ez-zağbî=ıbdıllıg bın gıdır ızzıgbı	",
            "&31=Abdullah Bin Hubeyk=ıbdıllıg bın gıbıyk	",
            "&32=Abdullah-ı İlâhî=ıbdıllıgı ılıgı	",
            "&33=Abdullah İmâmî İsfehânî=ıbdıllıg ımımı ısfıgını	",
            "&34=Abdullah-ı İsfehânî (Kutbüddîn-i İsfehbezî)=ıbdıllıgı ısfıgını kıdbıddını ısfıgbızı	",
            "&35=Abdullah El-kassâr=ıbdıllıg ılkıssır	",
            "&36=Abdullah Kaşgari=ıbdıllıg kısgırı	",
            "&37=Abdullah Mekkî Erzincânî=ıbdıllıg mıkkı ırzıncını	",
            "&38=Abdullah Bin Menâzil=ıbdıllıg bın mınızıl	",
            "&39=Abdullah Menûfî=ıbdıllıg mınıfı	",
            "&40=Abdullah Bin Muhammed Bin Abdurrahmân=ıbdıllıg bın mıgımmıd bın ıbdırrıgmın	",
            "&41=Abdullah Bin Muhammed Bâki-billah=ıbdıllıg bın mıgımmıd bıkıbıllıg	",
            "&42=Abdullah Bin Muhammed El-hadramî=ıbdıllıg bın mıgımmıd ılgıdrımı	",
            "&43=Abdullah Bin Muhammed Mürteiş=ıbdıllıg bın mıgımmıd mırdııs	",
            "&47=Abdullah Bin Mübârek=ıbdıllıg bın mıbırık	",
            "&48=Abdullah-ı Şemdînî=ıbdıllıgı sımdını	",
            "&49=Abdullah-ı Şüttârî=ıbdıllıgı sıddırı	",
            "&50=Abdullah Tercümân=ıbdıllıg dırcımın	",
            "&51=Abdullah İbni Vehb=ıbdıllıg ıbnı vıgb	",
            "&52=Abdullah Yâfiî=ıbdıllıg yıfıı	",
            "&53=Abdullah-ı Yemenî=ıbdıllıgı yımını	",
            "&54=Abdullah Bin Zeyd=ıbdıllıg bın zıyd	",
            "&55=Abdurrahmân Bin Ahmed (Abdurrahmân-ı Zâz)=ıbdırrıgmın bın ıgmıd ıbdırrıgmını zız	",
            "&56=Abdurrahmân Bin Ali Sekkâf=ıbdırrıgmın bın ılı sıkkıf	",
            "&57=Abdurrahmân Arvâsî=ıbdırrıgmın ırvısı	",
            "&58=Abdurrahmân Baba=ıbdırrıgmın bıbı	",
            "&59=Abdurrahmân Becelî=ıbdırrıgmın bıcılı	",
            "&60=Abdurrahmân Buceyremî=ıbdırrıgmın bıcıyrımı	",
            "&61=Abdurrahmân Efendi (Zileli)=ıbdırrıgmın ıfındı zılılı	",
            "&62=Abdurrahmân Efendi=ıbdırrıgmın ıfındı	",
            "&63=Abdurrahmân Gâzi=ıbdırrıgmın gızı	",
            "&64=Abdurrahmân-ı Harpûtî=ıbdırrıgmını gırpıdı	",
            "&65=Abdurrahmân Mağribî=ıbdırrıgmın mıgrıbı	",
            "&66=Abdurrahmân Bin Mehdî=ıbdırrıgmın bın mıgdı	",
            "&67=Abdurrahmân Bin Muhammed=ıbdırrıgmın bın mıgımmıd	",
            "&68=Abdurrahmân Bin Muhammed El-kayravânî=ıbdırrıgmın bın mıgımmıd ılkıyrıvını	",
            "&69=Abdurrahmân Bin Muhammed Es-sekkâf=ıbdırrıgmın bın mıgımmıd ıssıkkıf	",
            "&70=Abdurrahmân Nesîb Efendi=ıbdırrıgmın nısıb ıfındı	",
            "&71=Abdurrahmân Sâmi Niyâzi=ıbdırrıgmın sımı nıyızı	",
            "&72=Abdurrahmân Sultan=ıbdırrıgmın sıldın	",
            "&73=Abdurrahmân Tafsûncî=ıbdırrıgmın dıfsıncı	",
            "&74=Abdurrahmân Tâgî (Tâhî)=ıbdırrıgmın dıgı dıgı	",
            "&75=Abdurrahmân Bin Yûsuf Rûmî=ıbdırrıgmın bın yısıf rımı	",
            "&76=Abdüla'lâ Kureşî=ıbdılılı kırısı	",
            "&77=Abdülazîz Bekkine=ıbdılızız bıkkını	",
            "&78=Abdülazîz Debbağ=ıbdılızız dıbbıg	",
            "&79=Abdülazîz Dehlevî=ıbdılızız dıglıvı	",
            "&80=Abdülazîz Dîrînî=ıbdılızız dırını	",
            "&81=Abdülazîz Bin Ebû Revvâd=ıbdılızız bın ıbı rıvvıd	",
            "&82=Abdülbâki Efendi=ıbdılbıkı ıfındı	",
            "&83=Abdülehad=ıbdılıgıd	",
            "&84=Abdülehad Nûrî=ıbdılıgıd nırı	",
            "&85=Abdülehad Serhendî=ıbdılıgıd sırgındı	",
            "&86=Abdülfettâh-ı Bağdâdî Akrî=ıbdılfıddıgı bıgdıdı ıkrı	",
            "&87=Abdülfettâh-ı Velî=ıbdılfıddıgı vılı	",
            "&88=Abdülgafûr Dede (Seyyid)=ıbdılgıfır dıdı sıyyıd	",
            "&89=Abdülgafûr Hâlidî Müşâhidî=ıbdılgıfır gılıdı mısıgıdı	",
            "&90=Abdülganî Efendi=ıbdılgını ıfındı	",
            "&92=Abdülhâdi Bedevânî=ıbdılgıdı bıdıvını	",
            "&93=Abdülhak-ı Dehlevî=ıbdılgıkı dıglıvı	",
            "&94=Abdülhakîm Arvâsî=ıbdılgıkım ırvısı	",
            "&95=Abdülhakîm Hüseynî=ıbdılgıkım gısıynı	",
            "&96=Abdülhakîm-i Siyalkûtî=ıbdılgıkımı sıyılkıdı	",
            "&97=Abdülhâlık Goncdüvânî=ıbdılgılık gıncdıvını	",
            "&98=Abdülhamîd Bin Necîb Nûbânî=ıbdılgımıd bın nıcıb nıbını	",
            "&99=Abdülhamîd Şirvânî=ıbdılgımıd sırvını	",
            "&100=Abdülhay=ıbdılgıy	",
            "&101=Abdülhay Celvetî=ıbdılgıy cılvıdı	",
            "&102=Abdülhay Efendi (Öztoprak)=ıbdılgıy ıfındı ızdıprık	",
            "&103=Abdülkâdir Berzencî Hayderî=ıbdılkıdır bırzıncı gıydırı	",
            "&104=Abdülkâdir Deştûtî=ıbdılkıdır dısdıdı	",
            "&105=Abdülkâdir Dücânî=ıbdılkıdır dıcını	",
            "&106=Abdülkâdir Geylânî=ıbdılkıdır gıylını	",
            "&107=Abdülkâdir Sıddîkî=ıbdılkıdır sıddıkı	",
            "&108=Abdülkâhir Sühreverdî=ıbdılkıgır sıgrıvırdı	",
            "&109=Abdülkebîr Evliyâ=ıbdılkıbır ıvlıyı	",
            "&110=Abdülkerîm Cîlî=ıbdılkırım cılı	",
            "&111=Abdülkerîm Efendi=ıbdılkırım ıfındı	",
            "&112=Abdülkerîm Kâdirî=ıbdılkırım kıdırı	",
            "&113=Abdülkuddûs=ıbdılkıddıs	",
            "&114=Abdüllatîf Câmî=ıbdıllıdıf cımı	",
            "&115=Abdüllatîf Efendi (Pamuk Kâdı)=ıbdıllıdıf ıfındı pımık kıdı	",
            "&116=Abdüllatîf Kudsî=ıbdıllıdıf kıdsı	",
            "&117=Abdülmecîd Efendi=ıbdılmıcıd ıfındı	",
            "&118=Abdülmecîd Şirvânî=ıbdılmıcıd sırvını	",
            "&119=Abdülmelik Et-taberî=ıbdılmılık ıddıbırı	",
            "&120=Abdülmugîs Bin Züheyr=ıbdılmıgıs bın zıgıyr	",
            "&121=Abdülmu'tî Efendi=ıbdılmıdı ıfındı	",
            "&122=Abdülulâ=ıbdılılı	",
            "&123=Abdülvâhid-i Lâhorî=ıbdılvıgıdı lıgırı	",
            "&124=Abdülvâhid Bin Muhammed=ıbdılvıgıd bın mıgımmıd	",
            "&125=Abdülvâhid Bin Zeyd=ıbdılvıgıd bın zıyd	",
            "&126=Abdülvehhâb Buhârî=ıbdılvıggıb bıgırı	",
            "&127=Abdülvehhâb Gâzi=ıbdılvıggıb gızı	",
            "&128=Abdülvehhâb Bin İbrâhim=ıbdılvıggıb bın ıbrıgım	",
            "&129=Abdülvehhâb-ı Mısrî=ıbdılvıggıbı mısrı	",
            "&130=Abdülvehhâb Müttekî=ıbdılvıggıb mıddıkı	",
            "&131=Abdülvehhâb-ı Şa'rânî=ıbdılvıggıbı sırını	",
            "&132=Abdürrahîm Arvâsî=ıbdırrıgım ırvısı	",
            "&133=Abdürrahîm İstahrî=ıbdırrıgım ısdıgrı	",
            "&134=Abdürrahîm-i Merzifonî=ıbdırrıgımı mırzıfını	",
            "&135=Abdürrahîm Tırsî=ıbdırrıgım dırsı	",
            "&136=Abdürreşîd Sâhib Fârûkî=ıbdırrısıd sıgıb fırıkı	",
            "&137=Abdürrezzâk Ali Efendi=ıbdırrızzık ılı ıfındı	",
            "&138=Abdürrezzâk Dede=ıbdırrızzık dıdı	",
            "&139=Abdüsselâm Bin Meşîş Hasenî=ıbdıssılım bın mısıs gısını	",
            "&140=Acepşir Efendi=ıcıpsır ıfındı	",
            "&141=Açıkbaş Mahmûd Efendi=ıcıkbıs mıgmıd ıfındı	",
            "&142=Âdem-i Bennûrî=ıdımı bınnırı	",
            "&143=Adiyy Bin Müsâfir=ıdıyy bın mısıfır	",
            "&144=Ahıskalı Abdullah Efendi=ıgıskılı ıbdıllıg ıfındı	",
            "&145=Ahıskalı Ali Haydar Efendi=ıgıskılı ılı gıydır ıfındı	",
            "&146=Ahî Bayram=ıgı bıyrım	",
            "&147=Ahî Evran=ıgı ıvrın	",
            "&148=Ahî Sinan=ıgı sının	",
            "&149=Ahî Sirâc=ıgı sırıc	",
            "&150=Ahî Şorba=ıgı sırbı	",
            "&151=Ahmed Bin Abdurrahmân Es-sekkâf=ıgmıd bın ıbdırrıgmın ıssıkkıf	",
            "&152=Ahmed Abdülhak Radulevî=ıgmıd ıbdılgık rıdılıvı	",
            "&153=Ahmed El-alesî=ıgmıd ılılısı	",
            "&154=Ahmed Bin Alevî=ıgmıd bın ılıvı	",
            "&155=Ahmed Amiş Efendi=ıgmıd ımıs ıfındı	",
            "&156=Ahmed Bin Âsım Antâkî=ıgmıd bın ısım ındıkı	",
            "&157=Ahmed Bâbâ Tenbektî=ıgmıd bıbı dınbıkdı	",
            "&158=Ahmed-i Bedevî=ıgmıdı bıdıvı	",
            "&159=Ahmed Behlül=ıgmıd bıglıl	",
            "&160=Ahmed Berkî=ıgmıd bırkı	",
            "&161=Ahmed Bîcân=ıgmıd bıcın	",
            "&162=Ahmed Câhidî Efendi=ıgmıd cıgıdı ıfındı	",
            "&163=Ahmed Cüzeyrî (Cezerî)=ıgmıd cızıyrı cızırı	",
            "&164=Ahmed Dede=ıgmıd dıdı	",
            "&165=Ahmed Dede (Başmakçılı)=ıgmıd dıdı bısmıkcılı	",
            "&166=Ahmed Derdîrî=ıgmıd dırdırı	",
            "&167=Ahmed Diyobendî=ıgmıd dıyıbındı	",
            "&168=Ahmed Bin Ebû Bekr=ıgmıd bın ıbı bıkr	",
            "&169=Ahmed Bin Ebû Bekr Ayderûsî=ıgmıd bın ıbı bıkr ıydırısı	",
            "&170=Ahmed Bin Ebü'l-havârî=ıgmıd bın ıbılgıvırı	",
            "&171=Ahmed Bin Ebü'l-hayr Eş-şemâhî=ıgmıd bın ıbılgıyr ıssımıgı	",
            "&172=Ahmed Bin Ebû Verd=ıgmıd bın ıbı vırd	",
            "&173=Ahmed Eflâkî=ıgmıd ıflıkı	",
            "&174=Ahmed Eğribozî=ıgmıd ıgrıbızı	",
            "&175=Ahmed Feyzî Efendi=ıgmıd fıyzı ıfındı	",
            "&176=Ahmed Gazâlî=ıgmıd gızılı	",
            "&177=Ahmed Bin Hadraveyh=ıgmıd bın gıdrıvıyg	",
            "&178=Ahmed Hammâmî=ıgmıd gımmımı	",
            "&179=Ahmed Bin Hanbel=ıgmıd bın gınbıl	",
            "&181=Ahmed Bin Harb=ıgmıd bın gırb	",
            "&182=Ahmed Haznevî=ıgmıd gıznıvı	",
            "&183=Ahmed Hilmi Efendi=ıgmıd gılmı ıfındı	",
            "&184=Ahmed Hulûsi Efendi=ıgmıd gılısı ıfındı	",
            "&185=Ahmed Bin Hüseyin Ayderûsî=ıgmıd bın gısıyın ıydırısı	",
            "&186=Ahmed Bin İbrâhim Mesûhî=ıgmıd bın ıbrıgım mısıgı	",
            "&187=Ahmed Bin İbrâhim El-vâsıtî=ıgmıd bın ıbrıgım ılvısıdı	",
            "&188=Ahmed Bin İdrîs=ıgmıd bın ıdrıs	",
            "&189=Ahmed Bin İshak=ıgmıd bın ısgık	",
            "&190=Ahmed İzzet Efendi=ıgmıd ızzıd ıfındı	",
            "&191=Ahmed Kâbilî=ıgmıd kıbılı	",
            "&192=Ahmed Kâdirî=ıgmıd kıdırı	",
            "&193=Ahmed Kârazî Diyârıbekrî=ıgmıd kırızı dıyırıbıkrı	",
            "&194=Ahmed İbni Kemâl=ıgmıd ıbnı kımıl	",
            "&195=Ahmed Kihtû=ıgmıd kıgdı	",
            "&196=Ahmed Kuddûsî=ıgmıd kıddısı	",
            "&197=Ahmed Kuseyrî=ıgmıd kısıyrı	",
            "&198=Ahmed Mekkî Efendi=ıgmıd mıkkı ıfındı	",
            "&199=Ahmed Bin Mesrûk=ıgmıd bın mısrık	",
            "&200=Ahmed Bin Mevdûd Çeştî=ıgmıd bın mıvdıd cısdı	",
            "&201=Ahmed Bin Muhammed=ıgmıd bın mıgımmıd	",
            "&202=Ahmed Bin Muhammed Hânî El-esrem=ıgmıd bın mıgımmıd gını ılısrım	",
            "&203=Ahmed Bin Mûsâ El-acîl=ıgmıd bın mısı ılıcıl	",
            "&204=Ahmed Mürşidî Efendi=ıgmıd mırsıdı ıfındı	",
            "&205=Ahmed Nahlâvî=ıgmıd nıglıvı	",
            "&206=Ahmed Nâmıkî Câmî=ıgmıd nımıkı cımı	",
            "&207=Ahmed Necibî=ıgmıd nıcıbı	",
            "&208=Ahmed Nûbânî=ıgmıd nıbını	",
            "&209=Ahmed Bin Osman Şernûbî=ıgmıd bın ısmın sırnıbı	",
            "&210=Ahmed Bin Ömer Zeyla'î=ıgmıd bın ımır zıylıı	",
            "&211=Ahmed Raûfî=ıgmıd rııfı	",
            "&212=Ahmed Rıfâî=ıgmıd rıfıı	",
            "&213=Ahmed Saîd-i Fârûkî=ıgmıd sııdı fırıkı	",
            "&214=Ahmed Sârbân=ıgmıd sırbın	",
            "&215=Ahmed Satîha=ıgmıd sıdıgı	",
            "&216=Ahmed Sayyâd=ıgmıd sıyyıd	",
            "&217=Ahmed Bin Selmân En-neccâd=ıgmıd bın sılmın ınnıccıd	",
            "&218=Ahmed Es-senûsî=ıgmıd ıssınısı	",
            "&219=Ahmed Siyâhî=ıgmıd sıyıgı	",
            "&220=Ahmed Bin Süleyman Ervâdî=ıgmıd bın sılıymın ırvıdı	",
            "&221=Ahmed Şemseddîn Marmaravî=ıgmıd sımsıddın mırmırıvı	",
            "&222=Ahmed Şeybânî=ıgmıd sıybını	",
            "&223=Ahmed Şîrânî=ıgmıd sırını	",
            "&224=Ahmed-i Ticânî=ıgmıdı dıcını	",
            "&225=Ahmed Bin Üstâzü'l-a'zam=ıgmıd bın ısdızılızım	",
            "&226=Ahmed Bin Yahyâ El-celâ=ıgmıd bın yıgyı ılcılı	",
            "&227=Ahmed Yekdest Cüryânî=ıgmıd yıkdısd cıryını	",
            "&228=Ahmed Yesevî=ıgmıd yısıvı	",
            "&229=Ahmed Ez-zâhid=ıgmıd ızzıgıd	",
            "&230=Ahmed-i Zerrûk=ıgmıdı zırrık	",
            "&231=Ahmed Bin Zeyd=ıgmıd bın zıyd	",
            "&232=Ahmed Ziyâüddîn Efendi=ıgmıd zıyııddın ıfındı	",
            "&234=Ahmedullah=ıgmıdıllıg	",
            "&235=Ahmedü Bamba=ıgmıdı bımbı	",
            "&236=Ahnef El-hemedânî=ıgnıf ılgımıdını	",
            "&237=Ahnef Bin Kays=ıgnıf bın kıys	",
            "&238=Âişe Binti Câfer-i Sâdık=ıısı bındı cıfırı sıdık	",
            "&239=Akbıyık Sultan=ıkbıyık sıldın	",
            "&240=Akşemseddîn=ıksımsıddın	",
            "&241=Akyazılı Sultan=ıkyızılı sıldın	",
            "&242=Alâ Bin Ziyâd=ılı bın zıyıd	",
            "&243=Alâeddîn Âbizî=ılııddın ıbızı	",
            "&244=Alâeddîn Ali Erdebilî=ılııddın ılı ırdıbılı	",
            "&245=Alâeddîn Ali Esved Karahisârî (Kara Hoca)=ılııddın ılı ısvıd kırıgısırı kırı gıcı	",
            "&246=Alâeddîn Ali Fenârî (Alâeddîn Ali Bin Yûsuf)=ılııddın ılı fınırı ılııddın ılı bın yısıf	",
            "&247=Alâeddîn Arabî Efendi=ılııddın ırıbı ıfındı	",
            "&248=Alâeddîn-i Attâr=ılııddını ıddır	",
            "&249=Alâeddîn Goncdüvânî=ılııddın gıncdıvını	",
            "&250=Alâeddîn Bin Esad Lâhorî=ılııddın bın ısıd lıgırı	",
            "&251=Alâeddîn Halvetî=ılııddın gılvıdı	",
            "&252=Alâeddîn Harezmî=ılııddın gırızmı	",
            "&253=Alâeddîn Konevî=ılııddın kınıvı	",
            "&254=Alâeddîn-i Sâbir=ılııddını sıbır	",
            "&255=Alâeddîn Uşâkî=ılııddın ısıkı	",
            "&256=Alâüddevle Semnânî=ılııddıvlı sımnını	",
            "&257=Alevî Bin Abdullah=ılıvı bın ıbdıllıg	",
            "&258=Alevî Bin Ali=ılıvı bın ılı	",
            "&259=Alevî Bin Muhammed=ılıvı bın mıgımmıd	",
            "&260=Alevî Bin Muhammed Sâhib-üd-devîle=ılıvı bın mıgımmıd sıgıbıddıvılı	",
            "&261=Alevî Bin Üstâz-ül-a'zam=ılıvı bın ısdızılızım	",
            "&262=Ali Bin Abdullah Bin Abbâs=ılı bın ıbdıllıg bın ıbbıs	",
            "&263=Ali Bin Alevî Bin Muhammed=ılı bın ılıvı bın mıgımmıd	",
            "&264=Ali Behçet Efendi=ılı bıgcıd ıfındı	",
            "&265=Ali Bekkâ=ılı bıkkı	",
            "&266=Ali Bin Bendâr Sayrafî=ılı bın bındır sıyrıfı	",
            "&267=Ali Dede Bosnevî=ılı dıdı bısnıvı	",
            "&268=Ali Bin Ebû Bekr El-idrîsî=ılı bın ıbı bıkr ılıdrısı	",
            "&269=Ali Efendi=ılı ıfındı	",
            "&270=Ali Efendi (Midillili)=ılı ıfındı mıdıllılı	",
            "&271=Ali Bin Emrullah=ılı bın ımrıllıg	",
            "&272=Ali Ferâhî=ılı fırıgı	",
            "&273=Ali Bin Fudayl=ılı bın fıdıyl	",
            "&274=Ali Gâlib Vasfî Efendi=ılı gılıb vısfı ıfındı	",
            "&275=Ali Gav Sultan=ılı gıv sıldın	",
            "&276=Ali Hâdî (Nakî)=ılı gıdı nıkı	",
            "&277=Ali Hâfız=ılı gıfız	",
            "&278=Ali Bin Hamza El-isfehânî=ılı bın gımzı ılısfıgını	",
            "&279=Ali El-harîrî=ılı ılgırırı	",
            "&280=Ali Havâs Berlisî=ılı gıvıs bırlısı	",
            "&281=Ali Bin Heytî=ılı bın gıydı	",
            "&282=Ali İsfehânî=ılı ısfıgını	",
            "&283=Ali Kazvânî (Kîzvânî)=ılı kızvını kızvını	",
            "&284=Ali Mahallî=ılı mıgıllı	",
            "&285=Ali El-masîsî=ılı ılmısısı	",
            "&286=Ali Bin Meymûn Mağribî=ılı bın mıymın mıgrıbı	",
            "&287=Ali Bin Muhammed=ılı bın mıgımmıd	",
            "&288=Ali Bin Muhammed Bin Beşşâr=ılı bın mıgımmıd bın bıssır	",
            "&289=Ali Bin Mûsâ Feşli=ılı bın mısı fıslı	",
            "&290=Ali Bin Mustafa Ömerî=ılı bın mısdıfı ımırı	",
            "&291=Ali Bin Muvaffak=ılı bın mıvıffık	",
            "&292=Ali Müttekî El-hindî=ılı mıddıkı ılgındı	",
            "&293=Ali Müzeyyen=ılı mızıyyın	",
            "&294=Ali Nâtikî=ılı nıdıkı	",
            "&295=Ali Nebtîtî=ılı nıbdıdı	",
            "&296=Ali Osman Efendi=ılı ısmın ıfındı	",
            "&297=Ali Râmitenî=ılı rımıdını	",
            "&298=Ali Rızâ=ılı rızı	",
            "&299=Ali Rızâ Acara=ılı rızı ıcırı	",
            "&300=Ali Semerkandî=ılı sımırkındı	",
            "&301=Ali Septî=ılı sıpdı	",
            "&302=Ali Sincârî=ılı sıncırı	",
            "&303=Ali Şevnî=ılı sıvnı	",
            "&304=Ali Bin Şihâb=ılı bın sıgıb	",
            "&305=Ali Bin Yahyâ Geylânî=ılı bın yıgyı gıylını	",
            "&306=Ali Yeşrûtî=ılı yısrıdı	",
            "&307=Alihan Baba=ılıgın bıbı	",
            "&308=Alkame Bin Kays=ılkımı bın kıys	",
            "&309=Alvân Hamevî=ılvın gımıvı	",
            "&310=Alvarlı Muhammed Lütfi (Efe)=ılvırlı mıgımmıd lıdfı ıfı	",
            "&311=Amasyalı Seydî Halîfe=ımısyılı sıydı gılıfı	",
            "&312=A'meş (Süleymân Bin Mihrân)=ımıs sılıymın bın mıgrın	",
            "&313=Âmine-i Remliyye=ımınıı rımlıyyı	",
            "&314=Âmir Bin Abdullah=ımır bın ıbdıllıg	",
            "&315=Âmir Bin Abdullah Anberî=ımır bın ıbdıllıg ınbırı	",
            "&316=Ammâr-ı Yâser=ımmırı yısır	",
            "&317=Amr Bin Dînâr=ımr bın dınır	",
            "&318=Amr Bin Kays El-mülâî=ımr bın kıys ılmılıı	",
            "&319=Amr Bin Meymûn Evdî=ımr bın mıymın ıvdı	",
            "&320=Amr Bin Mürre=ımr bın mırrı	",
            "&321=Amr Bin Osman Mekkî=ımr bın ısmın mıkkı	",
            "&322=Amr Bin Şurahbil=ımr bın sırıgbıl	",
            "&323=Amr Bin Utbe=ımr bın ıdbı	",
            "&324=Ankaravî İsmâil Rusûhî=ınkırıvı ısmııl rısıgı	",
            "&325=Ankuzu Baba=ınkızı bıbı	",
            "&326=Arab Baba=ırıb bıbı	",
            "&327=Arab Dede=ırıb dıdı	",
            "&328=Arab Dede=ırıb dıdı	",
            "&329=Arabî Feştâlî El-mağribî=ırıbı fısdılı ılmıgrıbı	",
            "&330=Arabgirli Ömer Baba=ırıbgırlı ımır bıbı	",
            "&331=Ârif-i Dikgerânî=ırıfı dıkgırını	",
            "&332=Ârif-i Rivegerî=ırıfı rıvıgırı	",
            "&333=Arpacı Dede=ırpıcı dıdı	",
            "&334=Aslan Baba=ıslın bıbı	",
            "&335=Aslan Dede (Meczûb)=ıslın dıdı mıczıb	",
            "&336=Aşçı Yahyâ Baba=ıscı yıgyı bıbı	",
            "&337=Âşık Efendi=ısık ıfındı	",
            "&338=Âşık Paşa=ısık pısı	",
            "&339=Âşıklı Sultan=ısıklı sıldın	",
            "&340=Atâ Bin Ebû Rebâh=ıdı bın ıbı rıbıg	",
            "&341=Atâ Efendi=ıdı ıfındı	",
            "&342=Atâ El-ezrak=ıdı ılızrık	",
            "&343=Atâ Bin Meysere El-horasânî=ıdı bın mıysırı ılgırısını	",
            "&344=Atâ Süleymî=ıdı sılıymı	",
            "&345=Atâ Bin Yesâr=ıdı bın yısır	",
            "&346=Atâullah (Atâî Ahmed) Efendi=ıdııllıg ıdıı ıgmıd ıfındı	",
            "&347=Ateşbâz Velî=ıdısbız vılı	",
            "&348=Atpazarlı Osman Fadlı Efendi (Kutup Osman)=ıdpızırlı ısmın fıdlı ıfındı kıdıp ısmın	",
            "&349=Avdan Baba=ıvdın bıbı	",
            "&350=Avn Bin Abdullah=ıvn bın ıbdıllıg	",
            "&351=Ayderûsî=ıydırısı	",
            "&352=Ayderûsî (Abdullah Bin Abdullah)=ıydırısı ıbdıllıg bın ıbdıllıg	",
            "&353=Ayderûsî (Abdurrahmân Bin Mustafa)=ıydırısı ıbdırrıgmın bın mısdıfı	",
            "&354=Ayderûsî (Abdülkâdir Bin Şeyh)=ıydırısı ıbdılkıdır bın sıyg	",
            "&355=Ayderûsî (Ebû Muhammed)=ıydırısı ıbı mıgımmıd	",
            "&356=Ayderûsî (Muhammed Bin Abdullah)=ıydırısı mıgımmıd bın ıbdıllıg	",
            "&357=Ayderûsî (Şeyh Bin Abdullah)=ıydırısı sıyg bın ıbdıllıg	",
            "&358=Aydî Baba=ıydı bıbı	",
            "&359=Aynî Dede=ıynı dıdı	",
            "&360=Ayn-ül-kudât Hemedânî=ıynılkıdıd gımıdını	",
            "&361=Aynüzzemân Cemâleddîn-i Geylânî=ıynızzımın cımılıddını gıylını	",
            "&362=Aysâvî (Ahmed Bin Yûnus Ed-dımeşkî)=ıysıvı ıgmıd bın yınıs ıddımıskı	",
            "&363=Azerî Hamza Bin Ali=ızırı gımzı bın ılı	",
            "&364=Azîz Mahmûd Hüdâyî=ızız mıgmıd gıdıyı	",
            "&365=Aziz Nesefî=ızız nısıfı	",
            "&366=Azzâz Bin Müstevdî El-betâihî=ızzız bın mısdıvdı ılbıdııgı	",
            "&367=Baba Haydar Semerkandî=bıbı gıydır sımırkındı	",
            "&368=Baba Kemâl Cündî=bıbı kımıl cındı	",
            "&369=Baba Nîmetullah Nahçıvânî=bıbı nımıdıllıg nıgcıvını	",
            "&370=Baba Tâhir Uryân=bıbı dıgır ıryın	",
            "&371=Baba Yûsuf Sivrihisârî=bıbı yısıf sıvrıgısırı	",
            "&372=Babazâde=bıbızıdı	",
            "&373=Bahrak (Muhammed Bin Ömer)=bıgrık mıgımmıd bın ımır	",
            "&374=Bahri Dede=bıgrı dıdı	",
            "&375=Bahşî=bıgsı	",
            "&376=Bahşî Halîfe=bıgsı gılıfı	",
            "&377=Bâkıllânî=bıkıllını	",
            "&378=Bâlî Efendi (Sekrân)=bılı ıfındı sıkrın	",
            "&379=Baltalı Dede=bıldılı dıdı	",
            "&380=Balzat Hacı Baba Velî=bılzıd gıcı bıbı vılı	",
            "&381=Bâyezîd-i Bistâmî=bıyızıdı bısdımı	",
            "&382=Bayraklı Sultan=bıyrıklı sıldın	",
            "&383=Baytazzâde Hacı Abdullah=bıydızzıdı gıcı ıbdıllıg	",
            "&384=Bedirhan Bey=bıdırgın bıy	",
            "&385=Bedî'uddîn Sehârenpûrî=bıdııddın sıgırınpırı	",
            "&386=Bedî'uddîn Şâh Medâr=bıdııddın sıg mıdır	",
            "&387=Bedreddîn Serhendî=bıdrıddın sırgındı	",
            "&388=Behâeddîn Buhârî (Şâh-ı Nakşibend)=bıgııddın bıgırı sıgı nıksıbınd	",
            "&389=Behâeddîn Kışlakî=bıgııddın kıslıkı	",
            "&390=Behâeddîn Bin Lütfullah=bıgııddın bın lıdfıllıg	",
            "&391=Behâeddîn Meczûb El-kâdirî=bıgııddın mıczıb ılkıdırı	",
            "&394=Behâeddîn Zekeriyyâ (Muhammed Bin Kutbüddîn)=bıgııddın zıkırıyyı mıgımmıd bın kıdbıddın	",
            "&395=Behâeddînzâde (Muhyiddîn Muhammed Bin Behâeddîn)=bıgııddınzıdı mıgyıddın mıgımmıd bın bıgııddın	",
            "&396=Behiştî=bıgısdı	",
            "&397=Behlül-i Dânâ=bıglılı dını	",
            "&398=Behrullah Efendi=bıgrıllıg ıfındı	",
            "&399=Behzât-ı Velî=bıgzıdı vılı	",
            "&400=Bekâ Bin Batû=bıkı bın bıdı	",
            "&401=Bekâ Bin Mahled=bıkı bın mıglıd	",
            "&402=Bekkâr Rahîbî=bıkkır rıgıbı	",
            "&403=Bekr Bin Abdullah Müzenî=bıkr bın ıbdıllıg mızını	",
            "&404=Bekr El-meczûb=bıkr ılmıczıb	",
            "&405=Bekr Bin Ömer Fersânî=bıkr bın ımır fırsını	",
            "&406=Bekr Sıdkı Visâli=bıkr sıdkı vısılı	",
            "&407=Bekrî=bıkrı	",
            "&408=Bekrî (Ebü'l-mekârim)=bıkrı ıbılmıkırım	",
            "&409=Benâ Kureşî=bını kırısı	",
            "&410=Benli Sultan=bınlı sıldın	",
            "&411=Bennân El-hammâl=bınnın ılgımmıl	",
            "&412=Berbehârî=bırbıgırı	",
            "&413=Berdeî Sultan=bırdıı sıldın	",
            "&414=Bergamalı Hacı İbrâhim Efendi=bırgımılı gıcı ıbrıgım ıfındı	",
            "&415=Berk=bırk	",
            "&416=Beşik Baba=bısık bıbı	",
            "&417=Beşir Ağa=bısır ıgı	",
            "&418=Beşir Ağa=bısır ıgı	",
            "&419=Beşir-i Ebşir=bısırı ıbsır	",
            "&420=Beyzâde Efendi=bıyzıdı ıfındı	",
            "&421=Beyzâde Hacı Mehmed Nûri Efendi=bıyzıdı gıcı mıgmıd nırı ıfındı	",
            "&422=Beyzâde Mustafa Ahıskalı=bıyzıdı mısdıfı ıgıskılı	",
            "&423=Bîbî Cemâl Hâtun=bıbı cımıl gıdın	",
            "&424=Bîbî Hacere Hanım=bıbı gıcırı gınım	",
            "&425=Bilâl-i Ma'ribî=bılılı mırıbı	",
            "&426=Bilâl Bin Sa'd=bılıl bın sıd	",
            "&427=Birgivî=bırgıvı	",
            "&428=Bişr-i Hâfî=bısrı gıfı	",
            "&429=Bişr Bin Mansûr Es-süleymî=bısr bın mınsır ıssılıymı	",
            "&430=Boranlı Mustafa Baba=bırınlı mısdıfı bıbı	",
            "&431=Bosnalı Abdullah Efendi (Abdullah-ı Rûmî) / Abdullah-ı Bosnevî=bısnılı ıbdıllıg ıfındı ıbdıllıgı rımı  ıbdıllıgı bısnıvı	",
            "&432=Bostan Çelebi=bısdın cılıbı	",
            "&433=Bostancı Baba=bısdıncı bıbı	",
            "&434=Buhârî=bıgırı	",
            "&435=Burhâneddîn Muhakkık Tirmizî=bırgınıddın mıgıkkık dırmızı	",
            "&436=Burhâneddîn Bin Muhammed Eğridirî=bırgınıddın bın mıgımmıd ıgrıdırı	",
            "&437=Busayrî (Muhammed Bin Saîd Bin Hammâd)=bısıyrı mıgımmıd bın sııd bın gımmıd	",
            "&438=Bündâr Bin Hüseyin Şirâzî=bındır bın gısıyın sırızı	",
            "&439=Cabbâr Dede=cıbbır dıdı	",
            "&440=Câbir Bin Zeyd=cıbır bın zıyd	",
            "&441=Câfer Bin Abdürrahîm Kilâî=cıfır bın ıbdırrıgım kılıı	",
            "&442=Câfer Bin Ahmed Es-serrâc=cıfır bın ıgmıd ıssırrıc	",
            "&443=Câfer Efendi=cıfır ıfındı	",
            "&444=Câfer-i Huldî=cıfırı gıldı	",
            "&445=Câfer Huzâ=cıfır gızı	",
            "&446=Câfer Mekkî=cıfır mıkkı	",
            "&447=Câfer-i Sâdık=cıfırı sıdık	",
            "&448=Câfer-i Sâdık Bin Ali Ayderûsî=cıfırı sıdık bın ılı ıydırısı	",
            "&449=Câfer Bin Süleymân Dâbiî=cıfır bın sılıymın dıbıı	",
            "&450=Câkîr El-kürdî=cıkır ılkırdı	",
            "&451=Câmî Ahmed Dede=cımı ıgmıd dıdı	",
            "&452=Cârullah Veliyyüddîn Efendi=cırıllıg vılıyyıddın ıfındı	",
            "&453=Cebe Ali=cıbı ılı	",
            "&454=Celâl Ali Dede=cılıl ılı dıdı	",
            "&455=Celâl Tehâniserî=cılıl dıgınısırı	",
            "&456=Celâleddîn-i Devânî=cılılıddını dıvını	",
            "&457=Celâleddîn Ebû Yezid Pürânî=cılılıddın ıbı yızıd pırını	",
            "&458=Celâleddîn-i Hindî (Kutb-i Rabbânî, Kebîr-ül-evliyâ)=cılılıddını gındı kıdbı rıbbını kıbırılıvlıyı	",
            "&459=Celâleddîn-i Rûmî=cılılıddını rımı	",
            "&460=Celâleddîn Tebrîzî=cılılıddın dıbrızı	",
            "&461=Celâlzâde Mustafa Çelebi=cılılzıdı mısdıfı cılıbı	",
            "&462=Celâlzâde Sâlih Çelebi=cılılzıdı sılıg cılıbı	",
            "&463=Cemâl Halîfe=cımıl gılıfı	",
            "&464=Cemâleddîn Aksarâyî=cımılıddın ıksırıyı	",
            "&465=Cemâleddîn Ezherî=cımılıddın ızgırı	",
            "&466=Cemâleddîn Hansevî=cımılıddın gınsıvı	",
            "&467=Cemâleddîn Mahmûd Hulvî=cımılıddın mıgmıd gılvı	",
            "&468=Cemâleddîn-i Uşşâkî=cımılıddını ıssıkı	",
            "&469=Cemel Ali Dede (Turut)=cımıl ılı dıdı dırıd	",
            "&470=Cerrâhzâde=cırrıgzıdı	",
            "&471=Cevhere Berâsiyye=cıvgırı bırısıyyı	",
            "&472=Cezîrî=cızırı	",
            "&473=Cezûlî=cızılı	",
            "&474=Cihangirli Hasan Efendi=cıgıngırlı gısın ıfındı	",
            "&475=Cübeyr Bin Nüfeyr=cıbıyr bın nıfıyr	",
            "&476=Cüneyd-i Bağdâdî=cınıydı bıgdıdı	",
            "&477=Çandarlı Kara Halil Hayreddîn Paşa=cındırlı kırı gılıl gıyrıddın pısı	",
            "&478=Çelebi Abdülcelîl=cılıbı ıbdılcılıl	",
            "&479=Çelebi Ârif Küçük=cılıbı ırıf kıcık	",
            "&480=Çelebi Bustan=cılıbı bısdın	",
            "&481=Çelebi Cemâleddîn=cılıbı cımılıddın	",
            "&482=Çelebi Ferruh=cılıbı fırrıg	",
            "&483=Çelebi Halîfe=cılıbı gılıfı	",
            "&484=Çelebi Hüsâmeddîn=cılıbı gısımıddın	",
            "&485=Çelebi Hüsrev=cılıbı gısrıv	",
            "&486=Çerkez Şeyhi=cırkız sıygı	",
            "&487=Çırağ-ı Dehli=cırıgı dıglı	",
            "&488=Çomak Dede=cımık dıdı	",
            "&489=Dahmel Bin Abdullah=dıgmıl bın ıbdıllıg	",
            "&490=Da'lec Bin Ahmed=dılıc bın ıgmıd	",
            "&491=Dârendeli Muhammed Hilmi Efendi=dırındılı mıgımmıd gılmı ıfındı	",
            "&492=Dârendeli Ömer Rızâî=dırındılı ımır rızıı	",
            "&493=Dâvûd Bin A'zeb=dıvıd bın ızıb	",
            "&494=Dâvûd-i Halvetî=dıvıdı gılvıdı	",
            "&495=Dâvûd-i İskenderî=dıvıdı ıskındırı	",
            "&496=Dâvûd-i Kayserî=dıvıdı kıysırı	",
            "&497=Dâvûd Samadî=dıvıd sımıdı	",
            "&498=Dâvûd Bin Seyyid El-hüseynî=dıvıd bın sıyyıd ılgısıynı	",
            "&499=Dâvûd-i Tâî=dıvıdı dıı	",
            "&500=Daygam Bin Mâlik=dıygım bın mılık	",
            "&501=Dede Halîfe=dıdı gılıfı	",
            "&502=Dede Molla=dıdı mıllı	",
            "&503=Dede Ömer Rûşenî=dıdı ımır rısını	",
            "&504=Dedebağ Dede=dıdıbıg dıdı	",
            "&505=Dediği Sultan=dıdıgı sıldın	",
            "&506=Dehhâk Bin Müzâhim=dıggık bın mızıgım	",
            "&507=Dehlevî=dıglıvı	",
            "&508=Deli Birâder (Muhammed Bin Durmuş)=dılı bırıdır mıgımmıd bın dırmıs	",
            "&509=Demir Hoca=dımır gıcı	",
            "&510=Demirtaş Muhammedî=dımırdıs mıgımmıdı	",
            "&511=Derdimend Dede=dırdımınd dıdı	",
            "&512=Derviş Ahmed Semerkandî=dırvıs ıgmıd sımırkındı	",
            "&513=Derviş Hacı=dırvıs gıcı	",
            "&514=Derviş Muhammed=dırvıs mıgımmıd	",
            "&515=Deryâ Ali Baba=dıryı ılı bıbı	",
            "&516=Destîne Hâtun=dısdını gıdın	",
            "&517=Deveci Sultan=dıvıcı sıldın	",
            "&518=Deynekli Baba=dıynıklı bıbı	",
            "&519=Dırâr Bin Mürre=dırır bın mırrı	",
            "&520=Dimitrofçalı Muslihuddîn Efendi=dımıdrıfcılı mıslıgıddın ıfındı	",
            "&521=Dizdarzâde Ahmed Efendi=dızdırzıdı ıgmıd ıfındı	",
            "&522=Dursun Fakih (Tursun Fakih)=dırsın fıkıg dırsın fıkıg	",
            "&523=Ebdal Hasan=ıbdıl gısın	",
            "&524=Ebdal Kumral=ıbdıl kımrıl	",
            "&525=Ebdal Murâd=ıbdıl mırıd	",
            "&526=Ebnâsî (İbrâhim Bin Mûsâ)=ıbnısı ıbrıgım bın mısı	",
            "&527=Ebû Abdullah El-basrî=ıbı ıbdıllıg ılbısrı	",
            "&528=Ebû Abdullah Cavpâre=ıbı ıbdıllıg cıvpırı	",
            "&529=Ebû Abdullah Dîneverî=ıbı ıbdıllıg dınıvırı	",
            "&530=Ebû Abdullah Hadramî=ıbı ıbdıllıg gıdrımı	",
            "&531=Ebû Abdullah El-hâkan Es-sûfî=ıbı ıbdıllıg ılgıkın ıssıfı	",
            "&532=Ebû Abdullah El-kureşî=ıbı ıbdıllıg ılkırısı	",
            "&533=Ebû Abdullah Mağribî=ıbı ıbdıllıg mıgrıbı	",
            "&534=Ebû Abdullah El-mehâî=ıbı ıbdıllıg ılmıgıı	",
            "&535=Ebû Abdullah Merrakûşî=ıbı ıbdıllıg mırrıkısı	",
            "&536=Ebû Abdullah El-mukrî=ıbı ıbdıllıg ılmıkrı	",
            "&537=Ebû Abdullah Nibâcî=ıbı ıbdıllıg nıbıcı	",
            "&538=Ebû Abdullah-ı Rodbârî=ıbı ıbdıllıgı rıdbırı	",
            "&539=Ebû Abdullah Seczî=ıbı ıbdıllıg sıczı	",
            "&540=Ebû Abdullah Sübeyhî=ıbı ıbdıllıg sıbıygı	",
            "&541=Ebû Abdullah-ı Turuğbâdî=ıbı ıbdıllıgı dırıgbıdı	",
            "&542=Ebû Abdurrahmân Sülemî / Abdullah Bin Habib Sülemî=ıbı ıbdırrıgmın sılımı  ıbdıllıg bın gıbıb sılımı	",
            "&543=Ebû Affân Osman El-yemenî=ıbı ıffın ısmın ılyımını	",
            "&544=Ebû Ahmed Ebdâl Çeştî=ıbı ıgmıd ıbdıl cısdı	",
            "&545=Ebû Ahmed El-kalânisî=ıbı ıgmıd ılkılınısı	",
            "&546=Ebû Ali Cürcânî=ıbı ılı cırcını	",
            "&547=Ebû Ali Dekkâk=ıbı ılı dıkkık	",
            "&548=Ebû Ali Fârmedî=ıbı ılı fırmıdı	",
            "&549=Ebû Ali Müştevlî=ıbı ılı mısdıvlı	",
            "&550=Ebû Ali Rodbârî=ıbı ılı rıdbırı	",
            "&551=Ebû Ali Sekafî=ıbı ılı sıkıfı	",
            "&552=Ebû Amr Ez-zücâcî=ıbı ımr ızzıcıcı	",
            "&553=Ebû Bekr Bin Abdurrahmân Sekkâf=ıbı bıkr bın ıbdırrıgmın sıkkıf	",
            "&554=Ebû Bekr Ayderûs=ıbı bıkr ıydırıs	",
            "&555=Ebû Bekr El-betâihî=ıbı bıkr ılbıdııgı	",
            "&556=Ebû Bekr-i Dükkî=ıbı bıkrı dıkkı	",
            "&557=Ebû Bekr-i Ebherî=ıbı bıkrı ıbgırı	",
            "&558=Ebû Bekr Bin Ebû Vefâ=ıbı bıkr bın ıbı vıfı	",
            "&559=Ebû Bekr Ensârî=ıbı bıkr ınsırı	",
            "&560=Ebû Bekr El-ferrâ=ıbı bıkr ılfırrı	",
            "&561=Ebû Bekr Bin İyâş=ıbı bıkr bın ıyıs	",
            "&562=Ebû Bekr Kettânî=ıbı bıkr kıddını	",
            "&563=Ebû Bekr-i Kisâî Dîneverî=ıbı bıkrı kısıı dınıvırı	",
            "&564=Ebû Bekr-i Nessâc=ıbı bıkrı nıssıc	",
            "&565=Ebû Bekr Bin Sa'dân=ıbı bıkr bın sıdın	",
            "&566=Ebû Bekr Bin Sâlim Ayderûs=ıbı bıkr bın sılım ıydırıs	",
            "&567=Ebû Bekr Es-sekkâf=ıbı bıkr ıssıkkıf	",
            "&568=Ebû Bekr Eş-şelî=ıbı bıkr ıssılı	",
            "&570=Ebû Bekr Tamistânî=ıbı bıkr dımısdını	",
            "&571=Ebû Bekr Vâsıtî=ıbı bıkr vısıdı	",
            "&572=Ebû Bekr Verrâk=ıbı bıkr vırrık	",
            "&573=Ebû Bekr Ya'fûrî=ıbı bıkr yıfırı	",
            "&574=Ebû Câfer Haddâd El-kebîr=ıbı cıfır gıddıd ılkıbır	",
            "&575=Ebû Câfer El-meczûm=ıbı cıfır ılmıczım	",
            "&576=Ebû Câfer Bin Sinân=ıbı cıfır bın sının	",
            "&577=Ebû Hafs Haddâd En-nişâbûrî=ıbı gıfs gıddıd ınnısıbırı	",
            "&578=Ebû Hafs-ı Kebîr=ıbı gıfsı kıbır	",
            "&579=Ebû Hamza Bağdâdî=ıbı gımzı bıgdıdı	",
            "&580=Ebû Hamza Horasânî=ıbı gımzı gırısını	",
            "&581=Ebû Hâşim Sofî=ıbı gısım sıfı	",
            "&582=Ebû İdrîs Havlânî=ıbı ıdrıs gıvlını	",
            "&583=Ebû İmrân (Mûsâ)=ıbı ımrın mısı	",
            "&584=Ebû İshâk El-fezârî=ıbı ısgık ılfızırı	",
            "&585=Ebû İshâk İbrâhim Bin Müvelled=ıbı ısgık ıbrıgım bın mıvıllıd	",
            "&586=Ebû İshâk Şâmî-i Çeştî=ıbı ısgık sımıı cısdı	",
            "&587=Ebû İshâk-ı Şîrâzî=ıbı ısgıkı sırızı	",
            "&588=Ebû Midyen Mağribî=ıbı mıdyın mıgrıbı	",
            "&589=Ebû Muhammed El-basrî=ıbı mıgımmıd ılbısrı	",
            "&590=Ebû Muhammed Bayram Efendi=ıbı mıgımmıd bıyrım ıfındı	",
            "&591=Ebû Muhammed Cerîrî=ıbı mıgımmıd cırırı	",
            "&592=Ebû Muhammed Er-râsibî / Abdullah Bin Muhammed Râsibî=ıbı mıgımmıd ırrısıbı  ıbdıllıg bın mıgımmıd rısıbı	",
            "&593=Ebû Muhammed Râzî / Abdullah Bin Muhammed Râzî=ıbı mıgımmıd rızı  ıbdıllıg bın mıgımmıd rızı	",
            "&594=Ebû Muhammed Talhâ Bin Îsâ=ıbı mıgımmıd dılgı bın ısı	",
            "&595=Ebû Muhammed El-yemenî=ıbı mıgımmıd ılyımını	",
            "&596=Ebû Müslim Havlânî=ıbı mıslım gıvlını	",
            "&597=Ebû Nasr Pârisâ=ıbı nısr pırısı	",
            "&598=Ebû Osman Hîrî=ıbı ısmın gırı	",
            "&599=Ebû Osman Mağribî=ıbı ısmın mıgrıbı	",
            "&600=Ebû Saîd Bin El-arabî=ıbı sııd bın ılırıbı	",
            "&601=Ebû Saîd Ebü'l-hayr=ıbı sııd ıbılgıyr	",
            "&602=Ebû Saîd-i Fârûkî=ıbı sııdı fırıkı	",
            "&603=Ebû Saîd Bin Halef Bin Yahyâ Temîmî El-baccî=ıbı sııd bın gılıf bın yıgyı dımımı ılbıccı	",
            "&604=Ebû Saîd-i Harrâz=ıbı sııdı gırrız	",
            "&605=Ebû Saîd Kaylavî=ıbı sııd kıylıvı	",
            "&606=Ebû Saîd Bin Sun'ullah=ıbı sııd bın sınıllıg	",
            "&607=Ebû Süleymân Dârânî=ıbı sılıymın dırını	",
            "&608=Ebû Şu'be Hadramî=ıbı sıbı gıdrımı	",
            "&609=Ebû Tâhir Mahallî=ıbı dıgır mıgıllı	",
            "&610=Ebû Türâb-ı Nahşebî=ıbı dırıbı nıgsıbı	",
            "&611=Ebû Ubeyd El-busrî=ıbı ıbıyd ılbısrı	",
            "&612=Ebû Yâkûb Nehrecûrî=ıbı yıkıb nıgrıcırı	",
            "&613=Ebû Ya'zî Magribî=ıbı yızı mıgrıbı	",
            "&614=Ebû Yûsuf=ıbı yısıf	",
            "&615=Ebü'l-abbâs El-basîr=ıbılıbbıs ılbısır	",
            "&616=Ebü'l-abbâs Dîneverî=ıbılıbbıs dınıvırı	",
            "&617=Ebü'l-abbâs El-gamrî=ıbılıbbıs ılgımrı	",
            "&618=Ebü'l-abbâs El-harrâr=ıbılıbbıs ılgırrır	",
            "&619=Ebü'l-abbâs El-mülessem=ıbılıbbıs ılmılıssım	",
            "&620=Ebü'l-abbâs-ı Mürsî=ıbılıbbısı mırsı	",
            "&621=Ebü'l-abbâs Müstegânimî=ıbılıbbıs mısdıgınımı	",
            "&622=Ebü'l-abbâs Sebtî=ıbılıbbıs sıbdı	",
            "&623=Ebü'l-abbâs Seyyârî=ıbılıbbıs sıyyırı	",
            "&624=Ebü'l-berekât Emevî Hakkârî=ıbılbırıkıd ımıvı gıkkırı	",
            "&625=Ebü'l-fadl Ahmedî=ıbılfıdl ıgmıdı	",
            "&626=Ebü'l-hasan Ba'kûbî=ıbılgısın bıkıbı	",
            "&627=Ebü'l-hasan Bekrî=ıbılgısın bıkrı	",
            "&628=Ebü'l-hasan Cûsukî=ıbılgısın cısıkı	",
            "&629=Ebü'l-hasan-ı Eş'arî=ıbılgısını ısırı	",
            "&630=Ebü'l-hasan-ı Harkânî=ıbılgısını gırkını	",
            "&631=Ebü'l-hasan Kûsî=ıbılgısın kısı	",
            "&632=Ebü'l-hasan-ı Şâzilî=ıbılgısını sızılı	",
            "&633=Ebü'l-hayr El-akta=ıbılgıyr ılıkdı	",
            "&634=Ebü'l-hayr Fârûkî=ıbılgıyr fırıkı	",
            "&635=Ebü'l-hüseyin Nûrî=ıbılgısıyın nırı	",
            "&637=Ebüssü'ûd Ebü'l-aşâir El-bâzinî=ıbıssııd ıbılısıır ılbızını	",
            "&638=Ebüssü'ûd Efendi=ıbıssııd ıfındı	",
            "&639=Edebâlî (Üdebâlî)=ıdıbılı ıdıbılı	",
            "&640=Edhem Baba=ıdgım bıbı	",
            "&641=Edhem Çelebi=ıdgım cılıbı	",
            "&642=Elvân Çelebi=ılvın cılıbı	",
            "&643=Emânullah Lâhorî=ımınıllıg lıgırı	",
            "&644=Emîr Ahmed-i Buhârî=ımır ıgmıdı bıgırı	",
            "&645=Emîr-i Çin Şeyh Osman Efendi=ımırı cın sıyg ısmın ıfındı	",
            "&646=Emîr Gilân-i Vâşî=ımır gılını vısı	",
            "&647=Emîr Hayâlî Çelebi=ımır gıyılı cılıbı	",
            "&648=Emîr Hüsrev Dehlevî=ımır gısrıv dıglıvı	",
            "&649=Emîr Sultan=ımır sıldın	",
            "&650=Es'ad Efendi=ısıd ıfındı	",
            "&651=Es'ad Efendi (Sahhaflarşeyhizâde)=ısıd ıfındı sıggıflırsıygızıdı	",
            "&652=Es'ad İleri Hoca=ısıd ılırı gıcı	",
            "&653=Eskici Mehmed Dede=ıskıcı mıgmıd dıdı	",
            "&654=Esrâr Dede=ısrır dıdı	",
            "&655=Eşrefoğlu Rûmî=ısrıfıglı rımı	",
            "&656=Evhadüddîn Kirmânî=ıvgıdıddın kırmını	",
            "&657=Evliyâ Kâsım Paşa=ıvlıyı kısım pısı	",
            "&658=Evranos Dede=ıvrınıs dıdı	",
            "&659=Evzâî=ıvzıı	",
            "&660=Eyyûb-i Sahtiyânî=ıyyıbı sıgdıyını	",
            "&661=Fahreddîn-i Acemî=fıgrıddını ıcımı	",
            "&662=Fahreddîn-i Irâkî (İbrâhim Bin Şehriyâr Hemedânî)=fıgrıddını ırıkı ıbrıgım bın sıgrıyır gımıdını	",
            "&663=Fahreddîn-i Râzî=fıgrıddını rızı	",
            "&664=Fahri Efendi (Kulu)=fıgrı ıfındı kılı	",
            "&665=Fahr-ül-fârisî (Muhammed Bin İbrâhim Fârisî)=fıgrılfırısı mıgımmıd bın ıbrıgım fırısı	",
            "&666=Fakîrullah=fıkırıllıg	",
            "&667=Fâris Bin Îsâ Bağdâdî=fırıs bın ısı bıgdıdı	",
            "&668=Fâtıma Binti Müsennâ=fıdımı bındı mısınnı	",
            "&669=Fâtıma-i Nişâbûriyye=fıdımıı nısıbırıyyı	",
            "&670=Fâtih Ahmed Baba=fıdıg ıgmıd bıbı	",
            "&671=Fehim-i Arvâsî=fıgımı ırvısı	",
            "&672=Ferec Bin Abdullah=fırıc bın ıbdıllıg	",
            "&673=Ferec Meczûb=fırıc mıczıb	",
            "&674=Fereli Şeyh Sinan Efendi=fırılı sıyg sının ıfındı	",
            "&675=Ferîdüddîn-i Attâr=fırıdıddını ıddır	",
            "&676=Ferîdüddîn Genc-i Şeker=fırıdıddın gıncı sıkır	",
            "&677=Feth-i Mûsulî=fıdgı mısılı	",
            "&678=Fethullah Efendi=fıdgıllıg ıfındı	",
            "&679=Fethullah Evdehî=fıdgıllıg ıvdıgı	",
            "&680=Fethullah-ı Mûsulî=fıdgıllıgı mısılı	",
            "&681=Fethullah-ı Verkânisî=fıdgıllıgı vırkınısı	",
            "&682=Feyzullah Efendi=fıyzıllıg ıfındı	",
            "&683=Fudayl Bin İyâd=fıdıyl bın ıyıd	",
            "&684=Furûrî Mehmed Dede=fırırı mıgmıd dıdı	",
            "&685=Gamrî=gımrı	",
            "&686=Gani Baba=gını bıbı	",
            "&687=Garip Hâfız=gırıp gıfız	",
            "&688=Gavsî Ahmed Dede=gıvsı ıgmıd dıdı	",
            "&689=Gavs-ül-memdûh=gıvsılmımdıg	",
            "&690=Gazâlî=gızılı	",
            "&691=Geredeli Abdullah Efendi=gırıdılı ıbdıllıg ıfındı	",
            "&692=Geyikli Baba=gıyıklı bıbı	",
            "&693=Gökveli Sultan=gıkvılı sıldın	",
            "&694=Göncüzâde Kâsım Efendi=gıncızıdı kısım ıfındı	",
            "&695=Gözükızıl Mehmed Baba=gızıkızıl mıgmıd bıbı	",
            "&696=Gulâm Muhammed Ma'sûm=gılım mıgımmıd mısım	",
            "&697=Gül Baba=gıl bıbı	",
            "&699=Habîb-i Acemî=gıbıbı ıcımı	",
            "&700=Habîb Baba=gıbıb bıbı	",
            "&701=Habîb Ömerî Karamânî=gıbıb ımırı kırımını	",
            "&702=Habîb-i Râî=gıbıbı rıı	",
            "&703=Hâce Evliyâ-i Kebîr=gıcı ıvlıyıı kıbır	",
            "&704=Hâce Hasan Attâr=gıcı gısın ıddır	",
            "&705=Hâce İbrâhim=gıcı ıbrıgım	",
            "&706=Hâce Mevdûd Çeştî=gıcı mıvdıd cısdı	",
            "&707=Hâce Muhammed Bin Ebû Ahmed El-çeştî=gıcı mıgımmıd bın ıbı ıgmıd ılcısdı	",
            "&708=Hâce Osman Hârûnî=gıcı ısmın gırını	",
            "&709=Hâcegî Muhammed İmkenegî=gıcıgı mıgımmıd ımkınıgı	",
            "&710=Hacı Abdullah Efendi=gıcı ıbdıllıg ıfındı	",
            "&711=Hacı Ahmed Efendi=gıcı ıgmıd ıfındı	",
            "&712=Hacı Ali Efendi (Büyük)=gıcı ılı ıfındı bıyık	",
            "&713=Hacı Bayram-ı Velî=gıcı bıyrımı vılı	",
            "&714=Hacı Bektâş-ı Velî=gıcı bıkdısı vılı	",
            "&715=Hacı Dede=gıcı dıdı	",
            "&716=Hacı Dost Muhammed Kandehârî=gıcı dısd mıgımmıd kındıgırı	",
            "&717=Hacı Dursun Efendi=gıcı dırsın ıfındı	",
            "&718=Hacı Hıdır Efgân=gıcı gıdır ıfgın	",
            "&719=Hacı Mahmûd Efendi=gıcı mıgmıd ıfındı	",
            "&720=Hacı Muhammed Sâmî Efendi=gıcı mıgımmıd sımı ıfındı	",
            "&721=Hacı Muharrem Hilmi=gıcı mıgırrım gılmı	",
            "&722=Hacı Osman Nûri Kepenek=gıcı ısmın nırı kıpınık	",
            "&723=Hacı Ramazan=gıcı rımızın	",
            "&724=Hacı Şam Dede=gıcı sım dıdı	",
            "&725=Hacı Şerîf Zendenî=gıcı sırıf zındını	",
            "&726=Hacı Tevfik Rıfkı Efendi=gıcı dıvfık rıfkı ıfındı	",
            "&727=Hacı Torun Efendi=gıcı dırın ıfındı	",
            "&728=Hacı Veyiszâde Mustafa Efendi=gıcı vıyıszıdı mısdıfı ıfındı	",
            "&729=Hacım Sultan=gıcım sıldın	",
            "&730=Hâdimî=gıdımı	",
            "&731=Hâfız Osman Efendi=gıfız ısmın ıfındı	",
            "&732=Hâfız Sa'dullah=gıfız sıdıllıg	",
            "&733=Hakîm Çelebi=gıkım cılıbı	",
            "&734=Hakîm Senâî=gıkım sınıı	",
            "&735=Hakîm Süleymân Ata=gıkım sılıymın ıdı	",
            "&736=Hakîm-i Tirmizî=gıkımı dırmızı	",
            "&737=Halîfe Kızılayak=gılıfı kızılıyık	",
            "&738=Halîfe Mustafa Efendi=gılıfı mısdıfı ıfındı	",
            "&739=Halîmî Çelebi=gılımı cılıbı	",
            "&740=Halkalı Evliyâ=gılkılı ıvlıyı	",
            "&741=Hallâc-ı Mansûr=gıllıcı mınsır	",
            "&742=Hamdûn-ı Kassâr=gımdını kıssır	",
            "&744=Hamîdüddîn Nâgûrî=gımıdıddın nıgırı	",
            "&745=Hammâd Bin Müslim Debbâs=gımmıd bın mıslım dıbbıs	",
            "&746=Hânî Baba / Ahmed Hânî=gını bıbı  ıgmıd gını	",
            "&747=Hâris El-muhâsibî=gırıs ılmıgısıbı	",
            "&748=Harputlu Hacı Ömer Efendi=gırpıdlı gıcı ımır ıfındı	",
            "&749=Harputlu İshak Efendi=gırpıdlı ısgık ıfındı	",
            "&751=Hasan Adlî Efendi=gısın ıdlı ıfındı	",
            "&752=Hasan Bin Ali Askerî=gısın bın ılı ıskırı	",
            "&753=Hasan Baba=gısın bıbı	",
            "&754=Hasan-ı Basrî=gısını bısrı	",
            "&755=Hasan Can=gısın cın	",
            "&756=Hasan Dede=gısın dıdı	",
            "&757=Hasan Dede=gısın dıdı	",
            "&758=Hasan Ebû Halâve El-gazzî=gısın ıbı gılıvı ılgızzı	",
            "&759=Hasan Feyzi Efendi=gısın fıyzı ıfındı	",
            "&760=Hasan Hilmi Efendi=gısın gılmı ıfındı	",
            "&761=Hasan Hüsâmeddîn Uşâkî=gısın gısımıddın ısıkı	",
            "&762=Hasan Sekr Dımaşkî=gısın sıkr dımıskı	",
            "&763=Hasan Sezâî=gısın sızıı	",
            "&764=Hasîrîzâde (Şeyh Ahmed Muhtar Efendi)=gısırızıdı sıyg ıgmıd mıgdır ıfındı	",
            "&765=Hâşimî Emîr Osman=gısımı ımır ısmın	",
            "&766=Hâtim-i Esam=gıdımı ısım	",
            "&767=Hattat Hâfız Osman Efendi=gıddıd gıfız ısmın ıfındı	",
            "&768=Hayât Bin Kays El-harrânî=gıyıd bın kıys ılgırrını	",
            "&769=Hayreddîn Halil Bin Kâsım=gıyrıddın gılıl bın kısım	",
            "&770=Hayr-ün-nessâc=gıyrınnıssıc	",
            "&771=Helvacı Dede=gılvıcı dıdı	",
            "&772=Hıdır Baba=gıdır bıbı	",
            "&773=Hıdırlık Dede=gıdırlık dıdı	",
            "&774=Hıfnî (Hafnâvî)=gıfnı gıfnıvı	",
            "&775=Hızır Çelebi (Hızır Bey)=gızır cılıbı gızır bıy	",
            "&776=Hidâyetullah Erbilî=gıdıyıdıllıg ırbılı	",
            "&777=Himmet Efendi=gımmıd ıfındı	",
            "&778=Hoca Sâdeddîn Efendi=gıcı sıdıddın ıfındı	",
            "&779=Hocazâde=gıcızıdı	",
            "&780=Hucvîrî=gıcvırı	",
            "&781=Huysuz (Hırçın) Baba=gıysız gırcın bıbı	",
            "&782=Huzeyfetü'l-mer'âşî=gızıyfıdılmırısı	",
            "&783=Hübeyret-ül-basrî=gıbıyrıdılbısrı	",
            "&784=Hüsâmeddîn Mültânî=gısımıddın mıldını	",
            "&785=Hüsâmeddîn Nakşî=gısımıddın nıksı	",
            "&786=Hüsâmeddîn Pârisâ Belhî=gısımıddın pırısı bılgı	",
            "&787=Hüseyin Bin Ahmed El-mûsulî=gısıyın bın ıgmıd ılmısılı	",
            "&788=Hüseyin Dede=gısıyın dıdı	",
            "&789=Hüseyin Hulûsî Efendi (Üzüm Dedesi)=gısıyın gılısı ıfındı ızım dıdısı	",
            "&790=İbn-i Âbidîn=ıbnı ıbıdın	",
            "&791=İbn-i Ârif=ıbnı ırıf	",
            "&792=İbn-i Atâ=ıbnı ıdı	",
            "&793=İbn-i Atâullah=ıbnı ıdııllıg	",
            "&794=İbn-i Ayderûsî=ıbnı ıydırısı	",
            "&795=İbn-i Cevzî=ıbnı cıvzı	",
            "&796=İbn-i Fârid=ıbnı fırıd	",
            "&797=İbn-i Hafîf=ıbnı gıfıf	",
            "&798=İbn-i Kavvâm=ıbnı kıvvım	",
            "&799=İbn-i Muhayrız / Abdullah Bin Muhayrız=ıbnı mıgıyrız  ıbdıllıg bın mıgıyrız	",
            "&800=İbn-i Nüceyd=ıbnı nıcıyd	",
            "&801=İbn-i Semmâk=ıbnı sımmık	",
            "&802=İbn-i Üstâd-ül-a'zam=ıbnı ısdıdılızım	",
            "&803=İbn-i Vefâ (Ali Bin Muhammed)=ıbnı vıfı ılı bın mıgımmıd	",
            "&804=İbrâhim Bin Ali El-a'zeb=ıbrıgım bın ılı ılızıb	",
            "&805=İbrâhim Arvâsî=ıbrıgım ırvısı	",
            "&806=İbrâhim Desûkî=ıbrıgım dısıkı	",
            "&807=İbrâhim Bin Edhem=ıbrıgım bın ıdgım	",
            "&808=İbrâhim Efendi (Aşçı Dede)=ıbrıgım ıfındı ıscı dıdı	",
            "&809=İbrâhim Efendi (Mevlânâ Seyyid İbrâhim)=ıbrıgım ıfındı mıvlını sıyyıd ıbrıgım	",
            "&810=İbrâhim Gülşenî=ıbrıgım gılsını	",
            "&811=İbrâhim Hakkı Erzurûmî=ıbrıgım gıkkı ırzırımı	",
            "&812=İbrâhim-i Havvâs=ıbrıgımı gıvvıs	",
            "&813=İbrâhim Hayrânî=ıbrıgım gıyrını	",
            "&814=İbrâhim Kabâdî=ıbrıgım kıbıdı	",
            "&815=İbrâhim Medenî=ıbrıgım mıdını	",
            "&816=İbrâhim Şirvânî=ıbrıgım sırvını	",
            "&817=İbrâhim Tennûrî=ıbrıgım dınnırı	",
            "&818=İdris-i Muhtefî=ıdrısı mıgdıfı	",
            "&819=İğneci Baba=ıgnıcı bıbı	",
            "&820=İmâm-ı A'zam Ebû Hanîfe=ımımı ızım ıbı gınıfı	",
            "&821=İmâm Baba=ımım bıbı	",
            "&822=İmâm Efendi=ımım ıfındı	",
            "&823=İmâm-ı Rabbânî=ımımı rıbbını	",
            "&824=Îsâ Baba=ısı bıbı	",
            "&825=Îsâ Dede=ısı dıdı	",
            "&826=Îsâ Dede=ısı dıdı	",
            "&827=Îsâ Geylânî=ısı gıylını	",
            "&828=İsmâil Hakkı Bursevî=ısmııl gıkkı bırsıvı	",
            "&829=İsmâil Sirâceddîn Şirvânî=ısmııl sırıcıddın sırvını	",
            "&830=İsmâil Sirâceddîn-i Şirvânî=ısmııl sırıcıddını sırvını	",
            "&831=İsmâil Şirvânî=ısmııl sırvını	",
            "&832=İzmirli Osman Nûri Efendi=ızmırlı ısmın nırı ıfındı	",
            "&833=İzzeddîn Türkmânî=ızzıddın dırkmını	",
            "&834=Kabaşa=kıbısı	",
            "&835=Ka'b-ül-ahbâr=kıbılıgbır	",
            "&836=Kâdı Muhammed Zâhid=kıdı mıgımmıd zıgıd	",
            "&837=Kalburcu Şeyhi (Ahmed Dede)=kılbırcı sıygı ıgmıd dıdı	",
            "&838=Kanadıkırıkzâde Ali Efendi=kınıdıkırıkzıdı ılı ıfındı	",
            "&839=Kanadıkırıkzâde Mustafa Efendi=kınıdıkırıkzıdı mısdıfı ıfındı	",
            "&840=Kara Şems (Şemseddîn Ahmed Sivâsî)=kırı sıms sımsıddın ıgmıd sıvısı	",
            "&841=Karabaş Ali Efendi=kırıbıs ılı ıfındı	",
            "&842=Karabaş Sultan=kırıbıs sıldın	",
            "&843=Karaca Ahmed Sultan=kırıcı ıgmıd sıldın	",
            "&844=Karahisârî Abdürrahîm Efendi=kırıgısırı ıbdırrıgım ıfındı	",
            "&845=Kasım Aynî=kısım ıynı	",
            "&846=Kâsım Bin Muhammed=kısım bın mıgımmıd	",
            "&847=Kâsım Çelebi=kısım cılıbı	",
            "&848=Kâsım Halîfe=kısım gılıfı	",
            "&849=Kavukçu Ali Dede=kıvıkcı ılı dıdı	",
            "&850=Kayrevânî (Abdullah Bin Ebî Zeyd)=kıyrıvını ıbdıllıg bın ıbı zıyd	",
            "&851=Kayyûm-i Cihân Muhammed Seyfullah=kıyyımı cıgın mıgımmıd sıyfıllıg	",
            "&852=Kayyûm-i Zaman=kıyyımı zımın	",
            "&853=Kâzerûnî=kızırını	",
            "&854=Kemâl Ümmî=kımıl ımmı	",
            "&855=Kerîmüddîn Bâbâ Hasan Ebdâlî=kırımıddın bıbı gısın ıbdılı	",
            "&856=Kesikbaş Dede=kısıkbıs dıdı	",
            "&857=Keşşaf Hoca=kıssıf gıcı	",
            "&858=Kevserî=kıvsırı	",
            "&859=Kıbrıslı Hâfız Ali Efendi=kıbrıslı gıfız ılı ıfındı	",
            "&860=Kıbrıslı İbrâhim Sıdkı Efendi=kıbrıslı ıbrıgım sıdkı ıfındı	",
            "&861=Kılıç Dede=kılıc dıdı	",
            "&862=Kılıç Dede (Samsun)=kılıc dıdı sımsın	",
            "&863=Kılıçlı Ali Efendi=kılıclı ılı ıfındı	",
            "&864=Kırklar Dede=kırklır dıdı	",
            "&865=Kıyak Baba=kıyık bıbı	",
            "&866=Kocabıyık Eren Dede=kıcıbıyık ırın dıdı	",
            "&867=Koyun Baba (Denizli)=kıyın bıbı dınızlı	",
            "&868=Koyun Baba (Edirne)=kıyın bıbı ıdırnı	",
            "&869=Küçük Emir Efendi (Şimşir Baba)=kıcık ımır ıfındı sımsır bıbı	",
            "&870=Külhâni Ali Baba=kılgını ılı bıbı	",
            "&871=Kurtboğan Evliyâsı=kırdbıgın ıvlıyısı	",
            "&872=Kuşadalı İbrâhim Halvetî=kısıdılı ıbrıgım gılvıdı	",
            "&873=Kuşeyrî=kısıyrı	",
            "&874=Kutb-i Zaman (Seyyidcelâl Buhârî)=kıdbı zımın sıyyıdcılıl bıgırı	",
            "&875=Kutbüddîn İznîkî=kıdbıddın ıznıkı	",
            "&876=Kutbüddîn-i Bahtiyâr Kâkî=kıdbıddını bıgdıyır kıkı	",
            "&877=Ladikli Hacı Ahmed=lıdıklı gıcı ıgmıd	",
            "&878=Lâmiî Çelebi=lımıı cılıbı	",
            "&879=Leys Bin Sa'd=lıys bın sıd	",
            "&880=Lütfullah Efendi=lıdfıllıg ıfındı	",
            "&881=Lütfullah Efendi (El-evvel)=lıdfıllıg ıfındı ılıvvıl	",
            "&882=Lütfullah Üskübî=lıdfıllıg ıskıbı	",
            "&883=Lütfullah Üskübî=lıdfıllıg ıskıbı	",
            "&884=Mâcid El-kürdî=mıcıd ılkırdı	",
            "&885=Mahdûmzâde Ebü'l-kâsım=mıgdımzıdı ıbılkısım	",
            "&886=Mahmûd Çelebi=mıgmıd cılıbı	",
            "&887=Mahmûd Hayrânî=mıgmıd gıyrını	",
            "&888=Mahmûd-i İncirfagnevî=mıgmıdı ıncırfıgnıvı	",
            "&889=Mahmûd Ve İynel Sultanlar=mıgmıd vı ıynıl sıldınlır	",
            "&890=Mahmûd Kefevî=mıgmıd kıfıvı	",
            "&891=Mahmûd Sâminî=mıgmıd sımını	",
            "&892=Mahmûd Sûfî=mıgmıd sıfı	",
            "&893=Mahrez Bin Halef=mıgrız bın gılıf	",
            "&894=Mahrûk Efendi=mıgrık ıfındı	",
            "&895=Maksûd Dede=mıksıd dıdı	",
            "&896=Mâlik Bin Dînâr=mılık bın dınır	",
            "&897=Mâlik Bin Enes=mılık bın ınıs	",
            "&898=Mansûr Bin Ammâr=mınsır bın ımmır	",
            "&899=Mansûr El-betâihî=mınsır ılbıdııgı	",
            "&900=Ma'rûf-ı Kerhî=mırıfı kırgı	",
            "&901=Mazhar-ı Cân-ı Cânân=mızgırı cını cının	",
            "&902=Mecdüddîn Îsâ=mıcdıddın ısı	",
            "&903=Mecnun Dede=mıcnın dıdı	",
            "&904=Mehmed Behâeddîn Nakşibendî=mıgmıd bıgııddın nıksıbındı	",
            "&905=Mehmed Emîn Efendi=mıgmıd ımın ıfındı	",
            "&906=Mehmed Emîn Tokâdî=mıgmıd ımın dıkıdı	",
            "&907=Mehmed Eşref Efendi=mıgmıd ısrıf ıfındı	",
            "&908=Mehmed Hasîb Dürrî=mıgmıd gısıb dırrı	",
            "&909=Mehmed Zâhid Kotku=mıgmıd zıgıd kıdkı	",
            "&910=Mekârim En-nehr=mıkırım ınnıgr	",
            "&911=Mekhûl Eş-şâmî=mıkgıl ıssımı	",
            "&912=Memik Dede=mımık dıdı	",
            "&913=Merkez Efendi=mırkız ıfındı	",
            "&914=Merzûk Sârifî=mırzık sırıfı	",
            "&915=Mesrûk Bin El-ecdâ=mısrık bın ılıcdı	",
            "&916=Metbûlî=mıdbılı	",
            "&917=Mevlânâ Ebû Saîd Evbehî=mıvlını ıbı sııd ıvbıgı	",
            "&918=Mevlânâ Hâlid-i Bağdâdî=mıvlını gılıdı bıgdıdı	",
            "&919=Mevlânâ Hamîd-i Bingâlî=mıvlını gımıdı bıngılı	",
            "&920=Mevlânâ Hasan-ı Berkî=mıvlını gısını bırkı	",
            "&921=Mevlânâ Hayreddîn Etrâdî=mıvlını gıyrıddın ıdrıdı	",
            "&922=Mevlânâ Kâsım Ali Bedahşî=mıvlını kısım ılı bıdıgsı	",
            "&923=Mevlânâ Muhammed Rukıyye=mıvlını mıgımmıd rıkıyyı	",
            "&924=Mevlânâ Seyyid Hasan=mıvlını sıyyıd gısın	",
            "&925=Meyân Mîr=mıyın mır	",
            "&926=Meymûn Bin Mihrân=mıymın bın mıgrın	",
            "&927=Midyen Bin Ahmed El-eşmûnî=mıdyın bın ıgmıd ılısmını	",
            "&928=Mimşâd Ed-dîneverî=mımsıd ıddınıvırı	",
            "&929=Mîr Muhammed Numân=mır mıgımmıd nımın	",
            "&930=Mîrim Halvetî=mırım gılvıdı	",
            "&931=Mirzâ Hüsâmeddîn Ahmed=mırzı gısımıddın ıgmıd	",
            "&932=Misâlî Baba (Gül Baba)=mısılı bıbı gıl bıbı	",
            "&933=Miskâlî Efendi=mıskılı ıfındı	",
            "&934=Molla Arab=mıllı ırıb	",
            "&935=Molla Ayas=mıllı ıyıs	",
            "&936=Molla Câmî=mıllı cımı	",
            "&937=Molla Fenârî=mıllı fınırı	",
            "&938=Molla Gürânî=mıllı gırını	",
            "&939=Molla Halil Si'ridî=mıllı gılıl sırıdı	",
            "&940=Molla Hayâlî=mıllı gıyılı	",
            "&941=Molla Hüsrev=mıllı gısrıv	",
            "&942=Molla Osman Efendi=mıllı ısmın ıfındı	",
            "&943=Molla Yegân=mıllı yıgın	",
            "&944=Muhammed Bin Abdullah El-mürşidî=mıgımmıd bın ıbdıllıg ılmırsıdı	",
            "&945=Muhammed Bin Ahmed Fergal=mıgımmıd bın ıgmıd fırgıl	",
            "&946=Muhammed Bin Ali Mâzerî=mıgımmıd bın ılı mızırı	",
            "&947=Muhammed Bin Anân=mıgımmıd bın ının	",
            "&948=Muhammed Avfî=mıgımmıd ıvfı	",
            "&949=Muhammed Bâbâ Semmâsî=mıgımmıd bıbı sımmısı	",
            "&950=Muhammed Bahâeddîn Et-tavilî=mıgımmıd bıgııddın ıddıvılı	",
            "&951=Muhammed Bâkır=mıgımmıd bıkır	",
            "&952=Muhammed Bâkî-billah=mıgımmıd bıkıbıllıg	",
            "&953=Muhammed Bedahşî=mıgımmıd bıdıgsı	",
            "&954=Muhammed Buhârâlı=mıgımmıd bıgırılı	",
            "&955=Muhammed Cân=mıgımmıd cın	",
            "&956=Muhammed Cevâd=mıgımmıd cıvıd	",
            "&957=Muhammed Cisr=mıgımmıd cısr	",
            "&958=Muhammed Çelebi Sultan=mıgımmıd cılıbı sıldın	",
            "&959=Muhammed Bin Ebû Verd=mıgımmıd bın ıbı vırd	",
            "&960=Muhammed Efendi=mıgımmıd ıfındı	",
            "&961=Muhammed Emîn Efendi=mıgımmıd ımın ıfındı	",
            "&962=Muhammed Emin Erbilî=mıgımmıd ımın ırbılı	",
            "&963=Muhammed Bin Eslem Tûsî=mıgımmıd bın ıslım dısı	",
            "&964=Muhammed Ezherî=mıgımmıd ızgırı	",
            "&965=Muhammed Bin Fadl Belhî=mıgımmıd bın fıdl bılgı	",
            "&966=Muhammed Fethi Ali Efendi=mıgımmıd fıdgı ılı ıfındı	",
            "&967=Muhammed Hâcı Efdal=mıgımmıd gıcı ıfdıl	",
            "&968=Muhammed Bin Hâmid Tirmizî=mıgımmıd bın gımıd dırmızı	",
            "&969=Muhammed Bin Hanefiyye=mıgımmıd bın gınıfıyyı	",
            "&970=Muhammed Hânî=mıgımmıd gını	",
            "&971=Muhammed Harezmî=mıgımmıd gırızmı	",
            "&972=Muhammed Hâşim-i Keşmî=mıgımmıd gısımı kısmı	",
            "&973=Muhammed Hazîn=mıgımmıd gızın	",
            "&974=Muhammed Huccetullah=mıgımmıd gıccıdıllıg	",
            "&975=Muhammed Hüseyin Sâhib=mıgımmıd gısıyın sıgıb	",
            "&976=Muhammed Itrîs=mıgımmıd ıdrıs	",
            "&977=Muhammed İhsân=mıgımmıd ıgsın	",
            "&978=Muhammed İsmâil=mıgımmıd ısmııl	",
            "&979=Muhammed Bin Ka’b El-kurazî=mıgımmıd bın kıb ılkırızı	",
            "&980=Muhammed Kadri Hazîn=mıgımmıd kıdrı gızın	",
            "&981=Muhammed Kâmil Efendi=mıgımmıd kımıl ıfındı	",
            "&982=Muhammed Karsî=mıgımmıd kırsı	",
            "&983=Muhammed Kudâme=mıgımmıd kıdımı	",
            "&984=Muhammed Kudsî Bozkırî=mıgımmıd kıdsı bızkırı	",
            "&985=Muhammed Kumul Efendi=mıgımmıd kımıl ıfındı	",
            "&986=Muhammed Kutub=mıgımmıd kıdıb	",
            "&987=Muhammed Ma'sûm=mıgımmıd mısım	",
            "&988=Muhammed Ma'sûm Fârûkî=mıgımmıd mısım fırıkı	",
            "&989=Muhammed Mazhar=mıgımmıd mızgır	",
            "&990=Muhammed Mehdî=mıgımmıd mıgdı	",
            "&991=Muhammed Murâd Efendi=mıgımmıd mırıd ıfındı	",
            "&992=Muhammed Murâd Kazanî=mıgımmıd mırıd kızını	",
            "&993=Muhammed Nûreddîn Efendi=mıgımmıd nırıddın ıfındı	",
            "&994=Muhammed Nûreddîn Efendi=mıgımmıd nırıddın ıfındı	",
            "&995=Muhammed Osman Sâhib Müceddidî=mıgımmıd ısmın sıgıb mıcıddıdı	",
            "&996=Muhammed Ömer=mıgımmıd ımır	",
            "&997=Muhammed Bin Ömer (Kurd Efendi)=mıgımmıd bın ımır kırd ıfındı	",
            "&998=Muhammed Bin Ömer Hevârî=mıgımmıd bın ımır gıvırı	",
            "&999=Muhammed Pârisâ=mıgımmıd pırısı	",
            "&1000=Muhammed Reşîd=mıgımmıd rısıd	",
            "&1001=Muhammed Rûcî=mıgımmıd rıcı	",
            "&1002=Muhammed Sâdık=mıgımmıd sıdık	",
            "&1003=Muhammed Saîd=mıgımmıd sııd	",
            "&1004=Muhammed Saîd Fârûkî=mıgımmıd sııd fırıkı	",
            "&1005=Muhammed Sâmi (Sam Şeyhi)=mıgımmıd sımı sım sıygı	",
            "&1006=Muhammed Sıddîk=mıgımmıd sıddık	",
            "&1007=Muhammed Sıddîk Arvâsî=mıgımmıd sıddık ırvısı	",
            "&1008=Muhammed Sıddîk Keşmî=mıgımmıd sıddık kısmı	",
            "&1009=Muhammed Bin Sûka=mıgımmıd bın sıkı	",
            "&1010=Muhammed Şâzilî=mıgımmıd sızılı	",
            "&1011=Muhammed Şenâvî=mıgımmıd sınıvı	",
            "&1012=Muhammed Şeybânî=mıgımmıd sıybını	",
            "&1013=Muhammed Şüveymî=mıgımmıd sıvıymı	",
            "&1014=Muhammed Tevfîk Bosnevî=mıgımmıd dıvfık bısnıvı	",
            "&1015=Muhammed Ubeydullah Serhendî=mıgımmıd ıbıydıllıg sırgındı	",
            "&1016=Muhammed Urre=mıgımmıd ırrı	",
            "&1017=Muhammed Bin Vâsi’=mıgımmıd bın vısı	",
            "&1018=Muhammed Ziyâd=mıgımmıd zıyıd	",
            "&1019=Muhammed Zuğdân=mıgımmıd zıgdın	",
            "&1020=Muhammed Zühdi=mıgımmıd zıgdı	",
            "&1021=Muharrem Efendi=mıgırrım ıfındı	",
            "&1022=Muhibbullah-ı Mankpûrî=mıgıbbıllıgı mınkpırı	",
            "&1023=Muhyiddîn-i Arabî=mıgyıddını ırıbı	",
            "&1024=Muhyiddîn-i Dûstî=mıgyıddını dısdı	",
            "&1025=Muhyiddîn-i İskilibî=mıgyıddını ıskılıbı	",
            "&1026=Muhyiddîn Muhammed=mıgyıddın mıgımmıd	",
            "&1027=Muîdzâde (Molla Muhammed Bin Abdülazîz)=mııdzıdı mıllı mıgımmıd bın ıbdılızız	",
            "&1028=Muînüddîn-i Çeştî=mıınıddını cısdı	",
            "&1029=Murâd Baba=mırıd bıbı	",
            "&1030=Murâd-ı Münzâvî=mırıdı mınzıvı	",
            "&1031=Murâd-ı Velî=mırıdı vılı	",
            "&1032=Murtazâ Efendi=mırdızı ıfındı	",
            "&1033=Mûsa Fâkih=mısı fıkıg	",
            "&1034=Mûsâ Hâlidî (Şeyh Mûsâ)=mısı gılıdı sıyg mısı	",
            "&1035=Mûsâ Kâzım=mısı kızım	",
            "&1036=Mûsâ Bin Mâhîn Mardînî / Şeyhmuz Sultan=mısı bın mıgın mırdını  sıygmız sıldın	",
            "&1037=Mûsâ Sedranî=mısı sıdrını	",
            "&1038=Muslihuddîn Tavîl=mıslıgıddın dıvıl	",
            "&1039=Mustafa Âkif Efendi (Amasyalı)=mısdıfı ıkıf ıfındı ımısyılı	",
            "&1040=Mustafa Bekrî=mısdıfı bıkrı	",
            "&1041=Mustafa Efendi=mısdıfı ıfındı	",
            "&1042=Mustafa Fevzi Efendi (Eğinli)=mısdıfı fıvzı ıfındı ıgınlı	",
            "&1043=Mustafa Feyzi Efendi (Tekirdağlı)=mısdıfı fıyzı ıfındı dıkırdıglı	",
            "&1044=Mustafa Hâki Efendi=mısdıfı gıkı ıfındı	",
            "&1045=Mustafa İzzî Efendi=mısdıfı ızzı ıfındı	",
            "&1046=Mustafa Kuddûsî=mısdıfı kıddısı	",
            "&1047=Mustafa Mânevî Efendi=mısdıfı mınıvı ıfındı	",
            "&1048=Mustafa Bin Süleymân=mısdıfı bın sılıymın	",
            "&1049=Mustafa Yenicevî=mısdıfı yınıcıvı	",
            "&1050=Mutarrif Bin Abdullah=mıdırrıf bın ıbdıllıg	",
            "&1051=Mübarek Buhârî=mıbırık bıgırı	",
            "&1052=Müeyyedzâde Abdürrahîm Çelebi=mııyyıdzıdı ıbdırrıgım cılıbı	",
            "&1053=Müfti Abdülazîz Efendi=mıfdı ıbdılızız ıfındı	",
            "&1054=Münâvî (Yahyâ Bin Muhammed)=mınıvı yıgyı bın mıgımmıd	",
            "&1055=Müstekîmzâde Süleymân Sâdeddîn Efendi=mısdıkımzıdı sılıymın sıdıddın ıfındı	",
            "&1056=Müştâk Baba=mısdık bıbı	",
            "&1057=Nâbî=nıbı	",
            "&1058=Abdülganî Nablüsî=ıbdılgını nıblısı	",
            "&1059=Nâgûrî=nıgırı	",
            "&1060=Nalıncı Mîmî Dede=nılıncı mımı dıdı	",
            "&1061=Nasr Bin Abdürrezzâk=nısr bın ıbdırrızzık	",
            "&1062=Nasûh Çelebi Belgrâdî=nısıg cılıbı bılgrıdı	",
            "&1063=Nasûhî Üsküdârî=nısıgı ıskıdırı	",
            "&1064=Neccârzâde=nıccırzıdı	",
            "&1065=Neccârzâde Muhammed Sıddık=nıccırzıdı mıgımmıd sıddık	",
            "&1066=Necîb Efendi=nıcıb ıfındı	",
            "&1067=Necîbüddîn Mütevekkil=nıcıbıddın mıdıvıkkıl	",
            "&1068=Necîbüddîn-i Şîrâzî=nıcıbıddını sırızı	",
            "&1069=Necmeddîn Dâye Râzî=nıcmıddın dıyı rızı	",
            "&1070=Necmeddîn İmâd=nıcmıddın ımıd	",
            "&1071=Necmeddîn-i Kübrâ=nıcmıddını kıbrı	",
            "&1072=Nerkisecârî=nırkısıcırı	",
            "&1073=Nesevî=nısıvı	",
            "&1074=Nevevî=nıvıvı	",
            "&1075=Ni’metullah Geylânî=nımıdıllıg gıylını	",
            "&1076=Niyâzî-i Mısrî=nıyızıı mısrı	",
            "&1077=Nizâmeddîn Ebü’l-müeyyed=nızımıddın ıbılmııyyıd	",
            "&1078=Nizâmeddîn Evliyâ=nızımıddın ıvlıyı	",
            "&1079=Nizâmeddîn Hâmûş=nızımıddın gımıs	",
            "&1080=Nûdihî=nıdıgı	",
            "&1081=Nûr Muhammed Bedâyûnî=nır mıgımmıd bıdıyını	",
            "&1082=Nûr Muhammed Pütnî=nır mıgımmıd pıdnı	",
            "&1083=Nûredîn Baba=nırıdın bıbı	",
            "&1084=Nûreddîn Berîfkânî=nırıddın bırıfkını	",
            "&1085=Nûreddîn Cerrâhî=nırıddın cırrıgı	",
            "&1086=Nûreddîn Efendi=nırıddın ıfındı	",
            "&1087=Nûreddîn Taşkendî=nırıddın dıskındı	",
            "&1088=Nûreddînzâde Muslihuddîn=nırıddınzıdı mıslıgıddın	",
            "&1089=Nûri Efendi=nırı ıfındı	",
            "&1090=Nûri Efendi=nırı ıfındı	",
            "&1091=Nûrullah Efendi=nırıllıg ıfındı	",
            "&1092=Oflu Muhammed Emin Efendi=ıflı mıgımmıd ımın ıfındı	",
            "&1093=Osman Efendi=ısmın ıfındı	",
            "&1094=Osman Efendi=ısmın ıfındı	",
            "&1095=Osman Harrât=ısmın gırrıd	",
            "&1096=Osman El-hattâb=ısmın ılgıddıb	",
            "&1097=Osman Bin Merzûk El-kureşî=ısmın bın mırzık ılkırısı	",
            "&1098=Osman Nûrakûbî=ısmın nırıkıbı	",
            "&1099=Osman Es-serûcî=ısmın ıssırıcı	",
            "&1100=Osman Şirvânî=ısmın sırvını	",
            "&1101=Osman Et-tavilî=ısmın ıddıvılı	",
            "&1102=Ömer Bin Abdülazîz=ımır bın ıbdılızız	",
            "&1103=Ömer Baba=ımır bıbı	",
            "&1104=Ömer Füâdî=ımır fııdı	",
            "&1105=Ömer Hüdâî Baba=ımır gıdıı bıbı	",
            "&1106=Ömer Karadâğî=ımır kırıdıgı	",
            "&1107=Ömer Bin Mes’ûd El-bezzâr=ımır bın mısıd ılbızzır	",
            "&1108=Ömer Muhdâr Bin Abdurrahmân=ımır mıgdır bın ıbdırrıgmın	",
            "&1109=Ömer Nâimî Efendi=ımır nıımı ıfındı	",
            "&1110=Ömer Bin Saîd El-hemedânî=ımır bın sııd ılgımıdını	",
            "&1111=Ömer Şirvânî=ımır sırvını	",
            "&1112=Ömer Bin Zer=ımır bın zır	",
            "&1113=Ömer Ziyâeddîn Dağıstânî=ımır zıyııddın dıgısdını	",
            "&1114=Ömer Ziyâeddîn Tavîlî=ımır zıyııddın dıvılı	",
            "&1115=Pîr Ahmed Erzincânî=pır ıgmıd ırzıncını	",
            "&1116=Pîr Ali Aksarâyî=pır ılı ıksırıyı	",
            "&1117=Pîr Ali Dede=pır ılı dıdı	",
            "&1118=Pîr Ali Efendi=pır ılı ıfındı	",
            "&1119=Pîr Ali Efendi (Ali Bin Nasûh)=pır ılı ıfındı ılı bın nısıg	",
            "&1120=Pîr Cemâleddîn Abdurrahmân-ı Sânî=pır cımılıddın ıbdırrıgmını sını	",
            "&1121=Pîr Emir Sultan=pır ımır sıldın	",
            "&1122=Pîr Esad Sultan=pır ısıd sıldın	",
            "&1123=Pîr Fethullah=pır fıdgıllıg	",
            "&1124=Pîr İlyâs=pır ılyıs	",
            "&1125=Pîr Muhammed Erzincânî=pır mıgımmıd ırzıncını	",
            "&1126=Pîr Muhammed Gencevî=pır mıgımmıd gıncıvı	",
            "&1127=Pîr Şükrullah Halvetî=pır sıkrıllıg gılvıdı	",
            "&1128=Pîr Tevekkül=pır dıvıkkıl	",
            "&1129=Pirebi Sultan=pırıbı sıldın	",
            "&1130=Pîrî Baba=pırı bıbı	",
            "&1131=Pîrî Halîfe Hamîdî=pırı gılıfı gımıdı	",
            "&1132=Pîrî Halîfe Sultan=pırı gılıfı sıldın	",
            "&1133=Recep Enis Dede=rıcıp ınıs dıdı	",
            "&1134=Remlî Şâfiî=rımlı sıfıı	",
            "&1135=Resûl Zeki Efendi=rısıl zıkı ıfındı	",
            "&1136=Rislân Dımeşkî=rıslın dımıskı	",
            "&1137=Rûşen Efendi (Büyük Rûşen)=rısın ıfındı bıyık rısın	",
            "&1138=Rûzbehân Baklî=rızbıgın bıklı	",
            "&1139=Rükneddîn-i Çeştî=rıknıddını cısdı	",
            "&1140=Rükneddîn Ebü’l-feth=rıknıddın ıbılfıdg	",
            "&1141=Rüstem Halîfe Bursevî=rısdım gılıfı bırsıvı	",
            "&1142=Rüveym Bin Ahmed=rıvıym bın ıgmıd	",
            "&1143=Sâbit Ebü'l-meânî=sıbıd ıbılmıını	",
            "&1144=Sâbit Bin Eslem El-benânî=sıbıd bın ıslım ılbınını	",
            "&1145=Saçlı İbrâhim Efendi=sıclı ıbrıgım ıfındı	",
            "&1146=Sa'dî-i Şirâzî=sıdıı sırızı	",
            "&1147=Sâdık Ali Efendi=sıdık ılı ıfındı	",
            "&1148=Sâdık Efendi=sıdık ıfındı	",
            "&1149=Sadır Sultan=sıdır sıldın	",
            "&1150=Sadreddîn Bin Behâeddîn Zekeriyyâ=sıdrıddın bın bıgııddın zıkırıyyı	",
            "&1151=Sadreddîn Hayâvî=sıdrıddın gıyıvı	",
            "&1152=Sadreddîn-i Konevî=sıdrıddını kınıvı	",
            "&1153=Sadreddîn Muhammed Horasânî=sıdrıddın mıgımmıd gırısını	",
            "&1154=Sa'düddîn İsmâil Efendi=sıdıddın ısmııl ıfındı	",
            "&1155=Sa'düddîn-i Kaşgârî=sıdıddını kısgırı	",
            "&1156=Sâfî Âmidî Bolevî=sıfı ımıdı bılıvı	",
            "&1157=Safiyyüddîn Erdebilî=sıfıyyıddın ırdıbılı	",
            "&1158=Safranbolulu İsmâil Necâtî=sıfrınbılılı ısmııl nıcıdı	",
            "&1159=Saîd Bin Cübeyr=sııd bın cıbıyr	",
            "&1160=Saîd Bin Müseyyib=sııd bın mısıyyıb	",
            "&1161=Said Nursî=sııd nırsı	",
            "&1162=Said Şemid=sııd sımıd	",
            "&1163=Saidüddîn Fergânî=sııdıddın fırgını	",
            "&1164=Sâkıb Dede=sıkıb dıdı	",
            "&1165=Sâlih Baba=sılıg bıbı	",
            "&1166=Sâlih Bin Beşîr El-mürrî=sılıg bın bısır ılmırrı	",
            "&1167=Sâlih Efendi=sılıg ıfındı	",
            "&1168=Sâlih Gülâbî=sılıg gılıbı	",
            "&1169=Sâlih Sıbkî=sılıg sıbkı	",
            "&1170=Sâlim Bin Abdullah=sılım bın ıbdıllıg	",
            "&1171=Sâlim Şebşîrî=sılım sıbsırı	",
            "&1172=Saltuk Türkî=sıldık dırkı	",
            "&1173=Sandıklı Şeyhi Hasan Hamdi Efendi=sındıklı sıygı gısın gımdı ıfındı	",
            "&1174=Sarı Abdullah Efendi=sırı ıbdıllıg ıfındı	",
            "&1175=Sarı Ahmedzâde El-hâc Mehmed Efendi=sırı ıgmıdzıdı ılgıc mıgmıd ıfındı	",
            "&1176=Sarı Nâsuh=sırı nısıg	",
            "&1177=Sarı Saltuk=sırı sıldık	",
            "&1178=Sarı Yâkub=sırı yıkıb	",
            "&1179=Sefer Efendi=sıfır ıfındı	",
            "&1180=Sehl Bin Abdullah Tüsterî=sıgl bın ıbdıllıg dısdırı	",
            "&1181=Selâhaddîn Uşâkî=sılıgıddın ısıkı	",
            "&1182=Selâhaddîn Zerkûb=sılıgıddın zırkıb	",
            "&1183=Selâmi Ali Efendi=sılımı ılı ıfındı	",
            "&1184=Seleme Bin Dînâr=sılımı bın dınır	",
            "&1185=Selîm Fetihpûrî=sılım fıdıgpırı	",
            "&1186=Selîm Kırîmî=sılım kırımı	",
            "&1187=Selîm El-mesûtî=sılım ılmısıdı	",
            "&1188=Semnânî (Eşref Seyyid Emîr Cihângir)=sımnını ısrıf sıyyıd ımır cıgıngır	",
            "&1189=Semnûn Muhib=sımnın mıgıb	",
            "&1190=Senâullah-i Dehlevî=sınııllıgı dıglıvı	",
            "&1191=Senâullah Harâbâtî=sınııllıg gırıbıdı	",
            "&1192=Senâullah-i Sebnehlî=sınııllıgı sıbnıglı	",
            "&1193=Senûsî (Muhammed Bin Yûsuf)=sınısı mıgımmıd bın yısıf	",
            "&1194=Serrâc=sırrıc	",
            "&1195=Sertarîkzâde Mehmed Emin Efendi=sırdırıkzıdı mıgmıd ımın ıfındı	",
            "&1196=Serûcî=sırıcı	",
            "&1197=Seyfeddîn-i Fârûkî=sıyfıddını fırıkı	",
            "&1198=Seyfeddîn Halvetî=sıyfıddın gılvıdı	",
            "&1199=Seyfeddîn Menârî=sıyfıddın mınırı	",
            "&1200=Seyyid Abdülazîz=sıyyıd ıbdılızız	",
            "&1201=Seyyid Abdülhakîm=sıyyıd ıbdılgıkım	",
            "&1202=Seyyid Ahmed Çapakçurî=sıyyıd ıgmıd cıpıkcırı	",
            "&1203=Seyyid Ahmed Hicâbî=sıyyıd ıgmıd gıcıbı	",
            "&1204=Seyyid Ahmed-i Kebîr Er-rufâî=sıyyıd ıgmıdı kıbır ırrıfıı	",
            "&1205=Seyyid Ahmed Sünnetî=sıyyıd ıgmıd sınnıdı	",
            "&1206=Seyyid Ebû Ali Tunusî=sıyyıd ıbı ılı dınısı	",
            "&1207=Seyyid Emîr Burhân=sıyyıd ımır bırgın	",
            "&1208=Seyyid Emîr Hamza=sıyyıd ımır gımzı	",
            "&1209=Seyyid Emîr Külâl=sıyyıd ımır kılıl	",
            "&1210=Seyyid Hârun Velî=sıyyıd gırın vılı	",
            "&1211=Seyyid Hasan Berzencî=sıyyıd gısın bırzıncı	",
            "&1212=Seyyid Hasan Mükennâ=sıyyıd gısın mıkınnı	",
            "&1213=Seyyid Hüseyin Burhâneddîn Efendi=sıyyıd gısıyın bırgınıddın ıfındı	",
            "&1214=Seyyid Kâsım Tebrîzî=sıyyıd kısım dıbrızı	",
            "&1215=Seyyid Mahmûd Çağırgan=sıyyıd mıgmıd cıgırgın	",
            "&1216=Seyyid Muhammed Murâdî=sıyyıd mıgımmıd mırıdı	",
            "&1217=Seyyid Muhammed Osman El-mergânî=sıyyıd mıgımmıd ısmın ılmırgını	",
            "&1218=Seyyid Muhammed Şâh=sıyyıd mıgımmıd sıg	",
            "&1219=Seyyid Muslihiddîn Efendi=sıyyıd mıslıgıddın ıfındı	",
            "&1220=Seyyid Nizâm Efendi=sıyyıd nızım ıfındı	",
            "&1221=Seyyid Ömer Efendi=sıyyıd ımır ıfındı	",
            "&1222=Seyyid Radıyyüddîn Ali=sıyyıd rıdıyyıddın ılı	",
            "&1223=Seyyid Sâlih=sıyyıd sılıg	",
            "&1224=Seyyid Seyfullah Kâsım Efendi=sıyyıd sıyfıllıg kısım ıfındı	",
            "&1225=Seyyid Şerîf Cürcânî=sıyyıd sırıf cırcını	",
            "&1226=Seyyid Velâyet=sıyyıd vılıyıd	",
            "&1227=Seyyid Yahyâ Efendi=sıyyıd yıgyı ıfındı	",
            "&1228=Seyyidet Nefîse=sıyyıdıd nıfısı	",
            "&1229=Seyyidet Sekîne=sıyyıdıd sıkını	",
            "&1230=Sıbgatullah Arvâsî=sıbgıdıllıg ırvısı	",
            "&1231=Sıbgatullah-ı Bervecî=sıbgıdıllıgı bırvıcı	",
            "&1232=Sırrî-yi Sekatî=sırrıyı sıkıdı	",
            "&1233=Sinân Efendi=sının ıfındı	",
            "&1234=Sinân Erdebilî=sının ırdıbılı	",
            "&1235=Sinânüddîn Yûsuf Amâsî=sınınıddın yısıf ımısı	",
            "&1236=Sirâceddîn Ömer Halvetî=sırıcıddın ımır gılvıdı	",
            "&1237=Sivasî Abdülmecîd Efendi=sıvısı ıbdılmıcıd ıfındı	",
            "&1238=Sofu Baba=sıfı bıbı	",
            "&1239=Sofyalı Bâlî Efendi=sıfyılı bılı ıfındı	",
            "&1240=Somuncu Baba / Hamîd-i Aksarâyî=sımıncı bıbı  gımıdı ıksırıyı	",
            "&1241=Sûfî Allahyâr=sıfı ıllıgyır	",
            "&1242=Sultan Baba=sıldın bıbı	",
            "&1243=Sultan Dîvânî=sıldın dıvını	",
            "&1244=Sultan Sarı Baba=sıldın sırı bıbı	",
            "&1245=Sultân-ül-ulemâ=sıldınılılımı	",
            "&1246=Sultân-ül-ulemâ Behâeddîn Veled=sıldınılılımı bıgııddın vılıd	",
            "&1247=Behâeddîn Sultan Veled=bıgııddın sıldın vılıd	",
            "&1248=Sumâdî=sımıdı	",
            "&1249=Sumâdî=sımıdı	",
            "&1250=Süfyân Bin Abdullah Yemenî=sıfyın bın ıbdıllıg yımını	",
            "&1251=Süfyân-ı Sevrî=sıfyını sıvrı	",
            "&1252=Süfyân Bin Uyeyne=sıfyın bın ıyıynı	",
            "&1253=Sülemî=sılımı	",
            "&1254=Süleymân Çelebi=sılıymın cılıbı	",
            "&1255=Süleymân Halvetî (Beşikçizâde)=sılıymın gılvıdı bısıkcızıdı	",
            "&1256=Süleymân Hilmi Tunahan=sılıymın gılmı dınıgın	",
            "&1257=Süleymân Rüşdî Efendi=sılıymın rısdı ıfındı	",
            "&1258=Süleymân Sıdkı Efendi=sılıymın sıdkı ıfındı	",
            "&1259=Süleymân Zâtî Efendi=sılıymın zıdı ıfındı	",
            "&1260=Sümbül Baba=sımbıl bıbı	",
            "&1261=Sünbül Sinân Efendi=sınbıl sının ıfındı	",
            "&1262=Süveyd Sincârî=sıvıyd sıncırı	",
            "&1263=Şa'bân Dede=sıbın dıdı	",
            "&1264=Şa’bân-ı Velî=sıbını vılı	",
            "&1265=Şa'bî=sıbı	",
            "&1266=Şad-i Dîv=sıdı dıv	",
            "&1267=Şâfiî=sıfıı	",
            "&1268=Şâh Abdürrahim Dehlevî=sıg ıbdırrıgım dıglıvı	",
            "&1269=Şâh Ebü’l-meâlî=sıg ıbılmıılı	",
            "&1270=Şâh-ı A'lâ=sıgı ılı	",
            "&1271=Şâh Kubâd Şirvânî=sıg kıbıd sırvını	",
            "&1272=Şâh Muhammed Bedahşî=sıg mıgımmıd bıdıgsı	",
            "&1273=Şâh Muhammed Çelebi=sıg mıgımmıd cılıbı	",
            "&1274=Şâh Muhammed Ma’sûm Ömerî=sıg mıgımmıd mısım ımırı	",
            "&1275=Şah Raûf Ahmed=sıg rııf ıgmıd	",
            "&1276=Şâh Şücâ Kirmânî=sıg sıcı kırmını	",
            "&1277=Şâh Velî Ayıntabî=sıg vılı ıyındıbı	",
            "&1278=Şâh Veliyyullah-ı Dehlevî=sıg vılıyyıllıgı dıglıvı	",
            "&1279=Şâhî Mûytâb=sıgı mıydıb	",
            "&1280=Şâhidî İbrâhim Dede=sıgıdı ıbrıgım dıdı	",
            "&1281=Şakîk-i Belhî=sıkıkı bılgı	",
            "&1282=Şâkir Hamevî=sıkır gımıvı	",
            "&1283=Şebrîsî=sıbrısı	",
            "&1284=Şekmeti Mehmed Efendi=sıkmıdı mıgmıd ıfındı	",
            "&1285=Şems-i Tebrîzî=sımsı dıbrızı	",
            "&1286=Şemseddîn Îcî=sımsıddın ıcı	",
            "&1287=Şemseddîn İbn-i Münîr=sımsıddın ıbnı mınır	",
            "&1288=Şemseddîn Pâni-pütî (Hâce Şemseddîn Türk)=sımsıddın pınıpıdı gıcı sımsıddın dırk	",
            "&1289=Şerâfeddîn Ebû Ali Kalender=sırıfıddın ıbı ılı kılındır	",
            "&1290=Şerâfet Nevşâhî=sırıfıd nıvsıgı	",
            "&1291=Şerefüddîn Ahmed Bin Yahyâ Münîrî=sırıfıddın ıgmıd bın yıgyı mınırı	",
            "&1292=Şerîf Tlemsânî=sırıf dlımsını	",
            "&1293=Şerîfzâde Mehmed Efendi=sırıfzıdı mıgmıd ıfındı	",
            "&1294=Şeyh Abdullah Beytûşî=sıyg ıbdıllıg bıydısı	",
            "&1295=Şeyh Abdullah El-fâiz Dağıstânî=sıyg ıbdıllıg ılfıız dıgısdını	",
            "&1296=Şeyh Abdurrahmân=sıyg ıbdırrıgmın	",
            "&1297=Şeyh Abdurrahmân E- Bü'l-vefâ=sıyg ıbdırrıgmın ı bılvıfı	",
            "&1298=Şeyh Abdurrahmân Eşşâvirî=sıyg ıbdırrıgmın ıssıvırı	",
            "&1299=Şeyh Abdülhalim Efendi=sıyg ıbdılgılım ıfındı	",
            "&1300=Şeyh Abdülkâdir Kânî=sıyg ıbdılkıdır kını	",
            "&1301=Şeyh Abdülkâdir Muhâcir=sıyg ıbdılkıdır mıgıcır	",
            "&1302=Şeyh Ahmed Akvâvî=sıyg ıgmıd ıkvıvı	",
            "&1303=Şeyh Ahmed Efendi=sıyg ıgmıd ıfındı	",
            "&1304=Şeyh Ahmed Şemseddîn=sıyg ıgmıd sımsıddın	",
            "&1305=Şeyh Alâeddîn Rûşenî=sıyg ılııddın rısını	",
            "&1306=Şeyh Ali Behçet Efendi=sıyg ılı bıgcıd ıfındı	",
            "&1307=Şeyh Amr Rabbânî=sıyg ımr rıbbını	",
            "&1308=Şeyh Baba Resûl=sıyg bıbı rısıl	",
            "&1309=Şeyh Bâkır Ba'lekî=sıyg bıkır bılıkı	",
            "&1310=Şeyh Celâlüddîn Hürmâlî=sıyg cılılıddın gırmılı	",
            "&1311=Şeyh Derviş Hüseyin=sıyg dırvıs gısıyın	",
            "&1312=Şeyh Elvan=sıyg ılvın	",
            "&1313=Şeyh Gâlib Dede=sıyg gılıb dıdı	",
            "&1314=Şeyh Hâlid Cezerî=sıyg gılıd cızırı	",
            "&1315=Şeyh Hâlid Zibârî=sıyg gılıd zıbırı	",
            "&1316=Şeyh Hasan=sıyg gısın	",
            "&1317=Şeyh Hubeyşî=sıyg gıbıysı	",
            "&1318=Şeyh Hüseyin Basretî=sıyg gısıyın bısrıdı	",
            "&1319=Şeyh İbni Hatîb=sıyg ıbnı gıdıb	",
            "&1320=Şeyh İbni Nûh=sıyg ıbnı nıg	",
            "&1321=Şeyh İbrâhim Bin Ali=sıyg ıbrıgım bın ılı	",
            "&1322=Şeyh İbrâhim Ca'berî=sıyg ıbrıgım cıbırı	",
            "&1323=Şeyh İbrâhim Hakkı=sıyg ıbrıgım gıkkı	",
            "&1324=Şeyh İsmâil Enarânî=sıyg ısmııl ınırını	",
            "&1325=Şeyh İsmâil Rûmî=sıyg ısmııl rımı	",
            "&1326=Şeyh Kemâl Efendi=sıyg kımıl ıfındı	",
            "&1327=Şeyh Köstendilli Hasan Efendi=sıyg kısdındıllı gısın ıfındı	",
            "&1328=Şeyh Kutbeddîn=sıyg kıdbıddın	",
            "&1329=Şeyh Kutbüddîn Münevver=sıyg kıdbıddın mınıvvır	",
            "&1330=Şeyh Mahmûd=sıyg mıgmıd	",
            "&1331=Şeyh Mehmed Emin (Ramazan)=sıyg mıgmıd ımın rımızın	",
            "&1332=Şeyh Mehmed Ruhî Dede=sıyg mıgmıd rıgı dıdı	",
            "&1333=Şeyh Mehmed Şirvânî=sıyg mıgmıd sırvını	",
            "&1334=Şeyh Merzübân-ı Velî=sıyg mırzıbını vılı	",
            "&1335=Şeyh Mesut Horasanî=sıyg mısıd gırısını	",
            "&1336=Şeyh Muhammed Aynî=sıyg mıgımmıd ıynı	",
            "&1337=Şeyh Muhammed Bıserı (Kesikbaş)=sıyg mıgımmıd bısırı kısıkbıs	",
            "&1338=Şeyh Muhammed El-ma'ribî=sıyg mıgımmıd ılmırıbı	",
            "&1339=Şeyh Muhlis Baba=sıyg mıglıs bıbı	",
            "&1340=Şeyh Mustafa Bin Ebû Bekr=sıyg mısdıfı bın ıbı bıkr	",
            "&1341=Şeyh Nûreddîn=sıyg nırıddın	",
            "&1342=Şeyh Reyhan Adenî=sıyg rıygın ıdını	",
            "&1343=Şeyh Sabri=sıyg sıbrı	",
            "&1344=Şeyh Saçaklı=sıyg sıcıklı	",
            "&1345=Şeyh Sâdi=sıyg sıdı	",
            "&1346=Şeyh Safvetî=sıyg sıfvıdı	",
            "&1347=Şeyh Seydâ=sıyg sıydı	",
            "&1348=Şeyh Sinân=sıyg sının	",
            "&1349=Şeyh Süleymân=sıyg sılıymın	",
            "&1350=Şeyh Şâmil=sıyg sımıl	",
            "&1351=Şeyh Şihâbüddîn Sühreverdî=sıyg sıgıbıddın sıgrıvırdı	",
            "&1352=Şeyh Tâc=sıyg dıc	",
            "&1353=Şeyh Türkî=sıyg dırkı	",
            "&1354=Şeyh Ulemâ=sıyg ılımı	",
            "&1355=Şeyh Yûsuf Hemedânî=sıyg yısıf gımıdını	",
            "&1356=Şeyh-ün-neccâr=sıygınnıccır	",
            "&1357=Şeyhî=sıygı	",
            "&1359=Şeyh-ül-meşâyıh Behrâm=sıygılmısıyıg bıgrım	",
            "&1360=Ebû Bekr Şiblî=ıbı bıkr sıblı	",
            "&1361=Şihâbüddîn Ahmed Bin Ali=sıgıbıddın ıgmıd bın ılı	",
            "&1362=Şihâbüddîn Ahmed Sivâsî=sıgıbıddın ıgmıd sıvısı	",
            "&1363=Şihâbüddîn Ba'levî=sıgıbıddın bılıvı	",
            "&1364=Şihâbüddîn-i Sühreverdî=sıgıbıddını sıgrıvırdı	",
            "&1365=Şirvânî=sırvını	",
            "&1366=Şirvânî Es-sagîr=sırvını ıssıgır	",
            "&1367=Şuaybzâde Ali Âkif Efendi=sııybzıdı ılı ıkıf ıfındı	",
            "&1368=Şumeyt Bin Aclân=sımıyd bın ıclın	",
            "&1369=Şücâeddîn-i Karamânî=sıcııddını kırımını	",
            "&1370=Şühûdî Efendi=sıgıdı ıfındı	",
            "&1371=Şüsterî=sısdırı	",
            "&1372=Tâcüddîn İbrâhim Halvetî=dıcıddın ıbrıgım gılvıdı	",
            "&1373=Tâcüddîn İbrâhim Karamânî=dıcıddın ıbrıgım kırımını	",
            "&1374=Tâcüddîn Bin Rıfâî=dıcıddın bın rıfıı	",
            "&1375=Tacüddîn Velî=dıcıddın vılı	",
            "&1376=Tâcüddîn Zâhid-i Geylânî=dıcıddın zıgıdı gıylını	",
            "&1377=Tâc-ül-ârifîn (Ebü'l-vefâ)=dıcılırıfın ıbılvıfı	",
            "&1378=Taflâtî=dıflıdı	",
            "&1379=Tâhâ-i Hakkârî=dıgıı gıkkırı	",
            "&1380=Tâhir-i Bedahşî=dıgırı bıdıgsı	",
            "&1381=Tâhir-i Lâhorî=dıgırı lıgırı	",
            "&1382=Takıyyüddîn Ebû Bekr Kefevî=dıkıyyıddın ıbı bıkr kıfıvı	",
            "&1383=Takıyyüddîn Hısnî=dıkıyyıddın gısnı	",
            "&1384=Takıyyüddîn İbni Dakîk-ül-îd=dıkıyyıddın ıbnı dıkıkılıd	",
            "&1385=Takıyyüddîn Sübkî=dıkıyyıddın sıbkı	",
            "&1386=Taşkesenli Ahmed Efendi=dıskısınlı ıgmıd ıfındı	",
            "&1387=Taşkesenli İbrâhim Efendi=dıskısınlı ıbrıgım ıfındı	",
            "&1388=Tâvûs Bin Keysân=dıvıs bın kıysın	",
            "&1389=Tâzî=dızı	",
            "&1390=Tebâsî=dıbısı	",
            "&1391=Terzi Baba=dırzı bıbı	",
            "&1392=Terzizâde Ahmed Efendi=dırzızıdı ıgmıd ıfındı	",
            "&1393=Tesbih Baba=dısbıg bıbı	",
            "&1394=Tezveren Dede=dızvırın dıdı	",
            "&1395=Tokatlı Hayreddîn Efendi=dıkıdlı gıyrıddın ıfındı	",
            "&1396=Tokatlı İshak Zencânî=dıkıdlı ısgık zıncını	",
            "&1397=Topcu Dede=dıpcı dıdı	",
            "&1398=Tunusî (İbrâhim Bin Yahlef)=dınısı ıbrıgım bın yıglıf	",
            "&1399=Turhal Şeyhi Mustafa Efendi=dırgıl sıygı mısdıfı ıfındı	",
            "&1400=Tütünsüz Baba=dıdınsız bıbı	",
            "&1401=Ubeyde Bin Muhâcir=ıbıydı bın mıgıcır	",
            "&1402=Ubeydullah Bin Muhammed Bâki-billah=ıbıydıllıg bın mıgımmıd bıkıbıllıg	",
            "&1403=Ubeydullah-ı Ahrâr=ıbıydıllıgı ıgrır	",
            "&1404=Ubeydullah-ı Hakkârî=ıbıydıllıgı gıkkırı	",
            "&1405=Ukayl El-münbecî=ıkıyl ılmınbıcı	",
            "&1406=Ulu Ârif Çelebi=ılı ırıf cılıbı	",
            "&1407=Utbet-ül-gulâm=ıdbıdılgılım	",
            "&1408=Uzunca Hayreddîn=ızıncı gıyrıddın	",
            "&1409=Üç Kuzular=ıc kızılır	",
            "&1410=Üftâde=ıfdıdı	",
            "&1411=Üftâdezâde Kutub İbrâhim Efendi=ıfdıdızıdı kıdıb ıbrıgım ıfındı	",
            "&1412=Ünsî Hasan Efendi=ınsı gısın ıfındı	",
            "&1413=Üstâd-ül-a'zam=ısdıdılızım	",
            "&1414=Üryânî Mehmed Dede=ıryını mıgmıd dıdı	",
            "&1415=Üveys Medenî=ıvıys mıdını	",
            "&1416=Vânî Ahmed Efendi=vını ıgmıd ıfındı	",
            "&1417=Vânî Mehmed Efendi=vını mıgmıd ıfındı	",
            "&1418=Vecîhüddîn Ömer Efendi=vıcıgıddın ımır ıfındı	",
            "&1419=Ebül Vefâ Konevî=ıbıl vıfı kınıvı	",
            "&1420=Vehb Bin Münebbih=vıgb bın mınıbbıg	",
            "&1421=Vekî' Bin Cerrâh=vıkı bın cırrıg	",
            "&1422=Veli Dede=vılı dıdı	",
            "&1423=Veli Şemseddîn=vılı sımsıddın	",
            "&1424=Veliyyüddîn Oğlu Hacı Bulam=vılıyyıddın ıglı gıcı bılım	",
            "&1425=Venâî=vınıı	",
            "&1426=Veysel Karânî=vıysıl kırını	",
            "&1427=Vişnezâde=vısnızıdı	",
            "&1428=Vüheyb Bin Verd=vıgıyb bın vırd	",
            "&1429=Yâfiî=yıfıı	",
            "&1430=Yahyâ Efendi=yıgyı ıfındı	",
            "&1431=Yahyâ Bin Eksem=yıgyı bın ıksım	",
            "&1432=Yahyâ Îdilî=yıgyı ıdılı	",
            "&1433=Yahyâ Muammer Mezûrî İmâdî=yıgyı mıımmır mızırı ımıdı	",
            "&1434=Yahyâ Bin Muâz-ı Râzî=yıgyı bın mıızı rızı	",
            "&1435=Yahyâ Şirvânî=yıgyı sırvını	",
            "&1436=Ya’kûb-i Çerhî=yıkıbı cırgı	",
            "&1437=Ya’kûb Germiyânî=yıkıb gırmıyını	",
            "&1438=Yâkût-i Arşî=yıkıdı ırsı	",
            "&1439=Yanyalı Mustafa İsmet Efendi=yınyılı mısdıfı ısmıd ıfındı	",
            "&1440=Yâr Muhammed Kadîm Talkânî=yır mıgımmıd kıdım dılkını	",
            "&1441=Yâren Dede=yırın dıdı	",
            "&1442=Yayabaşızâde=yıyıbısızıdı	",
            "&1443=Yazıcızâde Muhammed Efendi=yızıcızıdı mıgımmıd ıfındı	",
            "&1444=Yûnus Emre=yınıs ımrı	",
            "&1445=Yûnus Bin Ubeyd=yınıs bın ıbıyd	",
            "&1446=Yûnus Bin Yûsuf Eş-şeybânî=yınıs bın yısıf ıssıybını	",
            "&1447=Yûsuf Bin Abdullah El-gürânî=yısıf bın ıbdıllıg ılgırını	",
            "&1448=Yûsuf Bin Abdürrahîm Aksûrî=yısıf bın ıbdırrıgım ıksırı	",
            "&1449=Yûsuf Bahri Efendi=yısıf bıgrı ıfındı	",
            "&1450=Yûsuf Bin Esbât=yısıf bın ısbıd	",
            "&1451=Yûsuf Hakîkî Baba=yısıf gıkıkı bıbı	",
            "&1452=Yûsuf Halvetî=yısıf gılvıdı	",
            "&1453=Yûsuf Harpûtî=yısıf gırpıdı	",
            "&1454=Yûsuf-ı Hemedânî=yısıfı gımıdını	",
            "&1455=Yûsuf Bin Hüseyin Râzî=yısıf bın gısıyın rızı	",
            "&1456=Yûsuf Kâmitî=yısıf kımıdı	",
            "&1457=Yûsuf Mahdûm=yısıf mıgdım	",
            "&1458=Yûsuf Bin Muhammed Çeştî=yısıf bın mıgımmıd cısdı	",
            "&1459=Yûsuf Nebhânî=yısıf nıbgını	",
            "&1460=Yûsuf Sinâneddîn-i Sîneçâk=yısıf sınınıddını sınıcık	",
            "&1461=Yünûnî=yınını	",
            "&1462=Zâhid=zıgıd	",
            "&1463=Zâhid İsfehânî=zıgıd ısfıgını	",
            "&1464=Zâhidü’l-kevserî=zıgıdılkıvsırı	",
            "&1465=Zâhid Yozgadî Şeyh Hacı Ahmed Efendi=zıgıd yızgıdı sıyg gıcı ıgmıd ıfındı	",
            "&1466=Zahîrüddîn Halvetî=zıgırıddın gılvıdı	",
            "&1467=Zâkirzâde Abdullah Efendi=zıkırzıdı ıbdıllıg ıfındı	",
            "&1468=Zarîfî Hasan Efendi=zırıfı gısın ıfındı	",
            "&1469=Zehâvî=zıgıvı	",
            "&1470=Zekeriyyâ Ensârî=zıkırıyyı ınsırı	",
            "&1471=Zekeriya Sultan=zıkırıyı sıldın	",
            "&1472=Zemlikânî=zımlıkını	",
            "&1473=Zemzem-i Hâssa=zımzımı gıssı	",
            "&1474=Zenbilli Ali Efendi=zınbıllı ılı ıfındı	",
            "&1475=Zengenî=zıngını	",
            "&1476=Zengî Atâ=zıngı ıdı	",
            "&1477=Zeyneddîn-i Hâfî=zıynıddını gıfı	",
            "&1478=Zeynelâbidîn=zıynılıbıdın	",
            "&1479=Zeynelâbidîn=zıynılıbıdın	",
            "&1480=Zeynelâbidîn Ayderûsî=zıynılıbıdın ıydırısı	",
            "&1481=Zeynelâbidîn Kayserânî=zıynılıbıdın kıysırını	",
            "&1482=Zeynelâbidîn Muhammed=zıynılıbıdın mıgımmıd	",
            "&1483=Zeynelâbidîn Münâvî=zıynılıbıdın mınıvı	",
            "&1484=Zeynullah Kazanî=zıynıllıg kızını	",
            "&1485=Zivingî=zıvıngı	",
            "&1486=Ziyâeddîn Bernî=zıyııddın bırnı	",
            "&1487=Ahmed Ziyâeddîn Gümüşhânevî=ıgmıd zıyııddın gımısgınıvı	",
            "&1488=Ziyâeddîn Nahşebî=zıyııddın nıgsıbı	",
            "&1489=Ziyâeddîn Nurşînî=zıyııddın nırsını	",
            "&1490=Ziyâeddîn Halîl Cündî=zıyııddın gılıl cındı	",
            "&1491=Züfer Bin Hüzeyl=zıfır bın gızıyl	",
            "&1492=Zührî=zıgrı	",
            "&1493=Zünnûn-i Mısrî=zınnını mısrı	",
            "&1494=Peygamber: Hz. Adem=ıdım	",
            "&1495=Peygamber: Hz. Şît=sıd	",
            "&1496=Peygamber: Hz. Nûh=nıg	",
            "&1497=Peygamber: Hz. İdris=ıdrıs	",
            "&1498=Peygamber: Hz. Hud=gıd	",
            "&1499=Peygamber: Hz. Hızır=gızır	",
            "&1500=Peygamber: Hz. Salih=sılıg	",
            "&1501=Peygamber: Hz. İbrahim=ıbrıgım	",
            "&1502=Peygamber: Hz. Lut=lıd	",
            "&1503=Peygamber: Hz. İsmâil=ısmııl	",
            "&1504=Peygamber: Hz. İshak=ısgak	",
            "&1505=Peygamber: Hz. Ya'kûb=yıkıb	",
            "&1506=Peygamber: Hz. Yûsuf=yısıf	",
            "&1507=Peygamber: Hz. Eyyûb=ıyyıb	",
            "&1508=Peygamber: Hz. Şuayb=sııyb	",
            "&1509=Peygamber: Hz. Musa=mısı	",
            "&1510=Peygamber: Hz. Harun=hırın	",
            "&1511=Peygamber: Hz. İlyas=ılyıs	",
            "&1512=Peygamber: Hz. Zülkifl=zılkıfl	",
            "&1513=Peygamber: Hz. Dâvûd=dıvıd	",
            "&1514=Peygamber: Hz. Süleyman=sılıymın	",
            "&1515=Peygamber: Hz. Yunus=yınıs	",
            "&1516=Peygamber: Hz. Zekeriyyâ=zıkırıyyı	",
            "&1517=Peygamber: Hz. Yahyâ=yıhyı	",
            "&1518=Peygamber: Hz. Îsâ=ısı	",
            "&1519=Peygamber: Hz. Muhammed=mıgımmıd	",
            "&1520=Peygamber: Hz. Zülkarneyn=zılkırnıyn	",
            "&1521=Peygamber: Hz. Lokman=lıkmın	",
            "&1522=Peygamber: Hz. Üzeyir=ızıyır	",
            "&1523=Peygamber: Hz. Elyesa=ılyısı	"

    };

    RecyclerView recyclerView;

    SearchView searchView;

    Toolbar toolbar;

    private Animator spruceAnimator;

    ArrayList<AndroidPOJO> list;

    @Override

    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);

        setContentView(R.layout.example_search_view);


        toolbar = findViewById(R.id.toolbar);

        /**Set ActionBar to Toolbar**/

        setSupportActionBar(toolbar);

        /**setDisplayHomeAsUpEnabled will display a back arrow button in Toolbar**/

        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        /**Set a Title to Toolbar**/

        getSupportActionBar().setTitle("SearchView");

        /**Set a Subtitle to Our Toolbar**/

        getSupportActionBar().setSubtitle("Search by Tapping on Search Icon");

        /**setNavigationOnClickListener will invloke when click on Back Button in Toolbar**/

        toolbar.setNavigationOnClickListener(new View.OnClickListener() {

            @Override

            public void onClick(View v) {

                finish();

            }

        });

        recyclerView = findViewById(R.id.recycler);

        /**Set Fixed Size to true**/

        recyclerView.setHasFixedSize(true);

        /**Set a Default Layout Manager**/

        recyclerView.setLayoutManager(new LinearLayoutManager(MainActivitySearchView.this));

        /**Set a ArrayList**/

        addData();

        /**Initialize the Custom Adaptor**/

        final CustomAdaptor adaptor = new CustomAdaptor(getApplicationContext(), list);
        recyclerView.setAdapter(adaptor);

        /**Set The Adaptor to RecyclerView**/


        /**When Click On List Item**/

        onClickList();


        /**Init SearchView**/

        searchView = (findViewById(R.id.searchView));

        /**Set a Hint Text for SearchView**/

        searchView.setQueryHint("Bir isim aratınız...");

        /**If iconified set to true then the SearchView is Collapsed, else Expand**/

        searchView.setIconified(false);

        /**When Close Icon is Clicked on SearchView**/

        searchView.setOnCloseListener(new SearchView.OnCloseListener() {

            @Override

            public boolean onClose() {

                /**Hide the Keyboard If Close Icon is Clicked**/

                InputMethodManager inputMethod = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);

                inputMethod.hideSoftInputFromWindow(searchView.getWindowToken(), 0);

                Toast.makeText(getApplicationContext(), "SearchView Closed!", Toast.LENGTH_SHORT).show();

                return true;

            }

        });

        /**When change text in SearchView, onClick Listener will execute**/

        searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {

            @Override

            public boolean onQueryTextSubmit(String query) {

                /**Hide the Keyboard When Submit**/

                InputMethodManager inputMethod = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);

                inputMethod.hideSoftInputFromWindow(searchView.getWindowToken(), 0);

                Toast.makeText(getApplicationContext(), "Search Completed...", Toast.LENGTH_SHORT).show();

                return true;

            }

            @Override

            public boolean onQueryTextChange(String newText) {

                /**Get the Current RecyclerView Adaptor**/

                CustomAdaptor adap = (CustomAdaptor) recyclerView.getAdapter();

                /**Now filter adaptor according to the Search Query(newText)**/

                adap.getFilter().filter(newText);

                onClickList();

                return true;

            }

        });

    }


    @Override

    public boolean onCreateOptionsMenu(Menu menu) {

        /**Inflate the menu in Toolbar with Menu Layout**/

        getMenuInflater().inflate(R.menu.menu_search, menu);

        /**Find the Menu Item using Item Id**/

        MenuItem searchItem = menu.findItem(R.id.example_search);

        final SearchView toolbarSearch = (SearchView) searchItem.getActionView();

        toolbarSearch.setQueryHint("Search...");

        toolbarSearch.setOnCloseListener(new SearchView.OnCloseListener() {

            @Override

            public boolean onClose() {

                /**Hide the Keyboard If Close Icon is Clicked**/

                InputMethodManager inputMethod = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);

                inputMethod.hideSoftInputFromWindow(toolbarSearch.getWindowToken(), 0);

                Toast.makeText(getApplicationContext(), "SearchView Closed!", Toast.LENGTH_SHORT).show();

                return true;

            }

        });

        /**When Click on Search Icon in Toolbar**/

        toolbarSearch.setOnQueryTextListener(new SearchView.OnQueryTextListener() {

            @Override

            public boolean onQueryTextSubmit(String query) {

                /**Hide the Keyboard When Submit**/

                InputMethodManager inputMethod = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);

                inputMethod.hideSoftInputFromWindow(toolbarSearch.getWindowToken(), 0);

                Toast.makeText(getApplicationContext(), "Search Completed...", Toast.LENGTH_SHORT).show();

                return true;

            }

            @Override

            public boolean onQueryTextChange(String newText) {

                /**Get the Current RecyclerView Adaptor**/

                CustomAdaptor adap = (CustomAdaptor) recyclerView.getAdapter();

                /**Now filter adaptor according to the Search Query(newText)**/

                adap.getFilter().filter(newText);

                onClickList();

                return true;

            }

        });

        return true;

    }

    private void onClickList() {

        /**On Click will invoke the interface RecyclerTouchListener**/

        final CustomAdaptor adapNew = (CustomAdaptor) recyclerView.getAdapter();

        adapNew.setClickListener(new CustomAdaptor.RecyclerTouchListener() {

            @Override

            public void onClickItem(View v, int position) {

                /**Rebind or Refresh The List Before Showing Toast**/

                list = adapNew.currentList();



                String androidName = list.get(position).getVersion();
                String androidNamex = list.get(position).getName();



                String s ="evliyalar/"+androidName+".txt";
                Intent i = new Intent(getApplicationContext(), EvliyalarGosterim.class);
                i.putExtra("Evliya", s);
                i.putExtra("Evliyaname", androidNamex);
                startActivity(i);
                Animatoo.animateFade(MainActivitySearchView.this);


            }

        });

    }

    private void addData() {

        list = new ArrayList<AndroidPOJO>();

        String startChar2 ="&";
        String endChar2 = "=";
        String startChar = "=";
        String endChar = "=";

        //ArrayList<String> list = new ArrayList<String>();
        for (int i = 0; i < number.length; i++) {
            String ekle = getStringBetweenTwoChars(number[i], startChar, endChar);
            String ekle2 = getStringBetweenTwoChars(number[i], startChar2, endChar2);
            list.add((new AndroidPOJO(ekle2, ekle)));

        }


    }

    public String getStringBetweenTwoChars(String input, String startChar, String endChar) {
        try {
            int start = input.indexOf(startChar);
            if (start != -1) {
                int end = input.indexOf(endChar, start + startChar.length());
                if (end != -1) {
                    return input.substring(start + startChar.length(), end);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return input; // return null; || return "" ;
    }
}